### ISSUE TITLE
EventUtility.ConstructEvent | Line Ending Mismatches

### ISSUE THREAD

**Issue by StephenMP** [stripe/stripe-dotnet#1506] opened 2019-02-07 14:42 UTC
Using .NET Core 2.1 Web API to catch Stripe Webhooks, I noticed an issue with line endings. Using the code:

```csharp
var eventJson = string.Empty;
using(var streamReader = new StreamReader(HttpContext.Request.Body))
{
    eventJson = await streamReader.ReadToEndAsync().ConfigureAwait(false);
}

var stripeWebhookEvent = EventUtility.ConstructEvent(eventJson, HttpContext.Request.Headers["Stripe-Signature"], _stripeWebhookSecret);
```

Results in the error `The signature for the webhook is not present in the Stripe-Signature header.`

I found out from #917 that it's because the body is being parsed using `\r\n` line endings and the body that was used for the HMAC signature from Stripe is using `\n` line endings. Thus, using the following code (notice the `.Replace("\r", "")`) resolves the issue:

```csharp
var eventJson = string.Empty;
using(var streamReader = new StreamReader(HttpContext.Request.Body))
{
    eventJson = (await streamReader.ReadToEndAsync().ConfigureAwait(false)).Replace("\r", "");
}

var stripeWebhookEvent = EventUtility.ConstructEvent(eventJson, HttpContext.Request.Headers["Stripe-Signature"], _stripeWebhookSecret);
```

Thus, it may be a good idea in the EventUtility to check to see if the line endings are `\r\n`, and if so, replace them for `\n`.

**Comment by ob-stripe** [comment] 2019-02-07 15:12
Hey @StephenMP, thanks for your message. This is definitely curious though, the raw body sent by Stripe uses `\n` for line endings, not `\r\n`, so I'm unsure what exactly inserts these `\r` characters in the payload. Maybe it's .NET itself that changes the newlines depending on the environment?

**Comment by ob-stripe** [comment] 2019-02-07 17:15
Haha, yeah. I'll try to dig a bit more, as I'd rather not alter the payload when the signature is being verified (on the off chance that the payload does include a legit `\r` character, this would break the signature verification).

**Comment by sumitkm** [comment] 2019-08-14 19:36
@ob-stripe Hi Oliver, I had similar issues with .NET 4.7.x (not Core). Turns out default JSON formatter formats line endings with \r\n and if you ask it to not format the JSON it removes all line endings. In the end I read the Request Body directly as string and use it to validate the Webhook signature, then fed the String to JSON deseralizer to get a JObject of other uses.

Question: Given every formatter on earth probably treats JSON formatting slightly differently why the decision to format payload from Stripe? (I don't expect/need any changes, just curious of the design decision).

**Comment by ob-stripe** [comment] 2019-08-14 22:23
HI @sumitkm, I'm not sure what you mean. Signature verification _must_ be done on the raw request body as a string, prior to JSON deserialization. The `EventUtility.ConstructEvent` method will first verify the signature, then (if the verification succeeded) deserialize the payload into an `Event` instance.

The library currently doesn't provide an easy way of just verifying the signature without also deserializing the payload, so if you want to do your own deserialization for whatever reason, the simplest thing to do is probably to call `EventUtility.ConstructEvent` and just discard the output.

**Comment by StephenMP** [comment] 2019-08-16 20:23
@sumitkm 

To add to @ob-stripe answer, the reason you use the raw request body as part of the signature and signature validation is to prevent any tampering that may have occurred between the sender and receiver. You should ALWAYS verify that what was sent to you was what you received.

**Comment by ob-stripe** [comment] 2019-08-18 01:15
Closing this issue since we were never able to reproduce the original problem (unexpected `\r` characters in the payload), but feel free to reply or open a new issue if you observe this happening.

**Closed by ob-stripe** 2019-08-18 01:15 UTC
