### ISSUE TITLE
SubscriptionItemService does not update metadata correctly

### ISSUE THREAD

**Issue by perpetualintelligence** [stripe/stripe-dotnet#2081] opened 2020-06-20 06:43 UTC
We want to update the subscription item's metadata for all our subscriptions but looks like the service does not update the metadata correctly... 

Even after the Update method the subscription item still shows the old metadata

**Specifically we are not able to remove an exiting metadata entry**

and 

**We are not able to update subscription item metadata for cancelled subscription.**

This is the sample code...

```
Stripe.SubscriptionService subscriptionService = new Stripe.SubscriptionService();
Stripe.SubscriptionListOptions subscriptionListOptions = new Stripe.SubscriptionListOptions()
            {
                Status = "all",
                Expand = new System.Collections.Generic.List<string>() { "data.customer", "data.items" }
            };
var allSubs = await subscriptionService.ListAsync(subscriptionListOptions);

foreach (var sub in allSubs)
{
        if (!StripeOperations.IsTrialOrActiveSubscription(sub))
        {
              continue;
        }

         foreach (var si in sub.Items.Data)
         {
                    Dictionary<string, string> newMetadata = new Dictionary<string, string>()
                    {
                          // an exiting metadata entry removed...
                          // {"deleted_key", "deleted_value"},
        
                           // an exiting metadata entry modified...
                           {"old_key1", "new_value1"},

                          // new metadata entry 
                           {"newkey1", "new_value2"},        
                    };

                    var options = new Stripe.SubscriptionItemUpdateOptions
                    {
                        Metadata = newMetadata
                    };

                    var service = new Stripe.SubscriptionItemService();

                   **// We are only updating metadata but this does not work correctly**
                    var newSI = await service.UpdateAsync(si.Id, options);
           }
 }
```

**Comment by remi-stripe** [comment] 2020-06-20 19:47
@perpetualintelligence Thanks for reaching out! I tried to reproduce your issue but a similar looking code works totally fine for me on the latest version of stripe-dotnet. Here's what I tried:

```
// Create Subscription with a plan
var optionsSub = new SubscriptionCreateOptions
{
  Customer = "cus_123",
  Items = new List<SubscriptionItemOptions>
  {
    new SubscriptionItemOptions
    {
      Plan = "plan_A",
      Metadata = new Dictionary<string, string>
      {
        {"key1", "value1"},
      },
    },
  },
};

var sub = new SubscriptionService().Create(optionsSub);
Console.WriteLine(sub.Items.Data[0]);

// Update SubscriptionItem's metadata
var optionsSI = new SubscriptionItemUpdateOptions
{
  Metadata = new Dictionary<string, string>
  {
    {"key1", "value1 updated"},
    {"key2", "value2 new"},
  },
};

var newSI = new SubscriptionItemService().Update(
  sub.Items.Data[0].Id,
  optionsSI
);
Console.WriteLine(newSI);
```

When I look at the output for those objects I get this for the first one:
```
  "metadata": {
    "key1": "value1"
  },
```

And for the second one
```
  "metadata": {
    "key1": "value1 updated",
    "key2": "value2 new"
  },
```

Would you be able to provide a bit more details about the issue and adding clear logs to each step so that I can better understand what's not working for you?

**Comment by perpetualintelligence** [comment] 2020-06-23 02:19
@remi-stripe 

We are facing issues in following 2 cases:

1. **Active Subscription**
For active subscription we are not able to delete an existing metadata element. You can add or edit the key or value but if you delete a metadata entry it is still present.

2. **Canceled Subscription**
If subscription is canceled then we are not able to update the metadata of the subscription items due to error Stripe.StripeException: Customer cus_H554fKgQNImkWW does not have a subscription with ID sub_H6wwqSzOTdddOe

**Comment by remi-stripe** [comment] 2020-06-23 02:34
@perpetualintelligence To delete the metadata key you have to explicitly set it to an empty string. I just tried the exact same code above but tweaking the value and it works and removes `key1` entirely.

```
var optionsSI = new SubscriptionItemUpdateOptions
{
  Metadata = new Dictionary<string, string>
  {
    {"key1", ""},
    {"key2", "value2 new"},
  },
};
```

For the second one, that is expected, you can update a canceled Subscription's metadata but you can't update the metadata of its SubscriptionItem today, you just get an API error.

**Comment by perpetualintelligence** [comment] 2020-06-23 02:45
@remi-stripe, thanks for case 1

For case 2:
We want our Trial subscription to record what products was used and once the Trial subscription is canceled or expired we have to update this subscription item metadata to know that it was subscribed and expired. User can activate the trial subscription again and they can subscribe to new products but not the once that are already subscribed and expired.

For this we were thinking to update the subscription item metadata to record a flag once the trial subscription is expired or canceled. But the error restricts this ?

The workaround could be to use Stripe web-hook, Is it OK to use Stipe Webhook and update the subscription items metadata 

// occurs 3 days before
 if (stripeEvent.Type == Stripe.Events.CustomerSubscriptionTrialWillEnd)
{
   // Record a flag on metadata for Subscription Item
  **// But will this again trigger a stripe subscription update web hook ?**
}

**Comment by remi-stripe** [comment] 2020-06-23 04:12
That option should work yes, it will trigger a `customer.subscription.updated` event in that case yes but you can just ignore it!

I'm going to close this issue out since it's not a bug with stripe-dotnet itself, I hope it's okay!

**Closed by remi-stripe** 2020-06-23 04:12 UTC

**Comment by perpetualintelligence** [comment] 2020-06-23 05:26
But why can't we update metadata for subscription item similar to that of a canceled subscription ?

**Comment by remi-stripe** [comment] 2020-06-23 15:43
@perpetualintelligence It's just a limitation of the API today, it's not a bug or limitation in stripe-dotnet itself. It might be supported in the future (I reported it internally) but for now this is just not possible unfortunately.

**Comment by Simonl9l** [comment] 2020-09-02 06:07
Also of note Subscription Item Metadata is not show in the dashboard, that make for support/reconciliation challenges.
