### ISSUE TITLE
OAuthTokenService Uses Incorrect Base URL for OAuth Requests After SDK Update

### ISSUE THREAD

**Issue by luca1897** [stripe/stripe-dotnet#3006] opened 2024-10-16 17:42 UTC
Hello,

After updating to the latest version of the Stripe .NET SDK (version 46.2.0), I've encountered an issue where the OAuth methods no longer function correctly. It appears that the SDK is concatenating the API base URL (https://api.stripe.com) instead of the Connect base URL (https://connect.stripe.com) when making OAuth requests.

### To Reproduce

Use the OAuthTokenService to request OAuth tokens with the following code snippet:
```csharp
var requestOptions = new RequestOptions
{
    ApiKey = ApiKey // Your API Key
};
var code = ""; // Your authorization code
var tokenService = new OAuthTokenService();
var tokenOptions = new OAuthTokenCreateOptions
{
    GrantType = "authorization_code",
    Code = code,
};
var stripeToken = await tokenService.CreateAsync(tokenOptions, requestOptions);
```

Run the code and observe the exception thrown.

An exception is thrown with the following message:
`Unrecognized request URL (POST: /oauth/token). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.`

Stack Trace:
```
Stripe.StripeException:
   at Stripe.LiveApiRequestor.ProcessResponse (Stripe.net, Version=46.2.0.0, Culture=neutral, PublicKeyToken=null: /_/src/Stripe.net/Infrastructure/Public/LiveApiRequestor.cs:245)
   at Stripe.LiveApiRequestor+<RequestAsync>d__33`1.MoveNext (Stripe.net, Version=46.2.0.0, Culture=neutral, PublicKeyToken=null: /_/src/Stripe.net/Infrastructure/Public/LiveApiRequestor.cs:110)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult
   at Stripe.StripeClient+<RequestAsync>d__36`1.MoveNext (Stripe.net, Version=46.2.0.0, Culture=neutral, PublicKeyToken=null: /_/src/Stripe.net/Infrastructure/Public/StripeClient.cs:154)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult
   at Stripe.Service+<RequestAsync>d__12`1.MoveNext (Stripe.net, Version=46.2.0.0, Culture=neutral, PublicKeyToken=null: /_/src/Stripe.net/Services/_base/Service.cs:100)
```

Below is a screenshot from my debugging session, where you can see that the URL used is https://api.stripe.com/oauth/token instead of the expected https://connect.stripe.com/oauth/token.
![error](https://github.com/user-attachments/assets/c85deede-b79c-4fd3-aa4f-5d428d3083cc)

Additional Details:
- The error message indicates that the request URL is unrecognized.
- Logging shows that the request is being made to https://api.stripe.com/oauth/token instead of https://connect.stripe.com/oauth/token.
- This behavior was not present in previous versions of the SDK and seems to have been introduced after last update.
- Example log entry:
`Name: POST /oauth/token, Type: HTTP, Call status: false, Duration: 19.6 ms, Data: https://api.stripe.com/oauth/token`

**Possible Implementation Error:**

It's possible that I might be making a mistake in my implementation. If that's the case, I would appreciate any guidance on how to correctly use the OAuthTokenService with the latest SDK version.

### Expected behavior

The OAuthTokenService should send requests to the Connect base URL (https://connect.stripe.com/oauth/token) rather than the API base URL.

### OS

Windows

### .NET version

.NET Framework 4.8

### Library version

stripe-dotnet 46.2.0

### API version

2024-09-30.acacia

### Additional context

- The issue seems to have arisen after updating the SDK.
- If I'm incorrectly using the OAuthTokenService, please let me know the proper way to implement it with the current SDK.

**Comment by bwinklesky** [comment] 2024-10-16 23:13
I recieved the same error in 46.2.0

**Comment by jar-stripe** [comment] 2024-10-17 00:05
@luca1897 @bwinklesky : thank you for reporting and confirming this issue, and sorry for the trouble!  I took a look and think I see what the issue is.  Currently working on a fix; we'll update you when it is out and ready to use.

As a work around (if you are able to use a workaround), pass the StripeConfiguration.StripeClient as a constructor argument to OAuthTokenService:

```csharp
var requestOptions = new RequestOptions
{
    ApiKey = ApiKey // Your API Key
};
var code = ""; // Your authorization code
var tokenService = new OAuthTokenService(StripeConfiguration.StripeClient); // <<< Explicitly pass the client here
var tokenOptions = new OAuthTokenCreateOptions
{
    GrantType = "authorization_code",
    Code = code,
};
var stripeToken = await tokenService.CreateAsync(tokenOptions, requestOptions);
```

This is in essence what is going on internal to the SDK, but this code takes a slightly different path that will not have this issue.

**Comment by jar-stripe** [comment] 2024-10-17 19:58
Thanks for the update @luca1897 !  A fix should be coming shortly in the released SDK package; I'm glad this worked for you in the mean time.

**Comment by jar-stripe** [comment] 2024-10-21 16:29
Quick update: this was fixed in https://github.com/stripe/stripe-dotnet/pull/3007 and is now available in https://github.com/stripe/stripe-dotnet/releases/tag/v46.2.1!

**Closed by jar-stripe** 2024-10-21 16:29 UTC
Labels: bug
