### ISSUE TITLE
BalanceTransactionListOptions doesn0t support StripeAccount-option

### ISSUE THREAD

**Issue by ToniFankhauser** [stripe/stripe-dotnet#2253] opened 2020-11-19 14:22 UTC
I need to get all the payouts for the connected accounts.
in Stripe Sigma i can do this:
```
select * from connected_account_balance_transactions where type='payout'
  order by created desc
```
If i try to do this in .net, there's no way i can specify the StripeAccount-option. Without the StripeAccount-option i only get the payout for the main-account, but not for the connected accounts:
```
var options = new BalanceTransactionListOptions
  {
  StripeAccount = "acct_1HYmcBAS6IVINMCo",
  Type = "payout",
   };
var service = new BalanceTransactionService();
StripeList<BalanceTransaction> balanceTransactions = service.List(options);
```
What's the correct way (or workaround) to get this working?

**Comment by remi-stripe** [comment] 2020-11-19 16:48
@ToniFankhauser When you want to make a call on behalf of a connected account you have to use the `Stripe-Account` header which is documented [here](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header). Since this is a custom header on an HTTP request, it's not passed as an API parameter today and is passed separately in each library. In stripe-dotnet, this is done using `RequestOptions`. So your code would look like this:
```
// Parameters to filter the BalanceTransaction returned
var options = new BalanceTransactionListOptions
{
  Type = "payout",
};

// Configure which connected account the request is made on
var requestOptions = new RequestOptions();
requestOptions.StripeAccount = "acct_1HYmcBAS6IVINMCo";

var service = new BalanceTransactionService();
StripeList<BalanceTransaction> balanceTransactions = service.List(options, requestOptions);
```

I hope this helps unblock you! I'm going to close the issue as it's not a bug with the library and is a question about our API instead. Don't hesitate to talk to our support team if you have more questions: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-11-19 16:48 UTC
