### ISSUE TITLE
Serialization error - property is doubled on ChargeCreateOptions

### ISSUE THREAD

**Issue by Piachu91** [stripe/stripe-dotnet#1411] opened 2018-12-05 08:24 UTC
Hi,
for this problem 'luckily' my setup and env shouldn't matter - are you aware that `ChargeCreateOptions` have doubled JsonProperties using the same name?
```
 [JsonProperty("source")]
        public string SourceId { get; set; }
  [JsonProperty("source")]
   public CardCreateNestedOptions SourceCard { get; set; }
```

Because of this I'm unable to serialize this class to Json (logging purposes):

> Newtonsoft.Json.JsonSerializationException: A member with the name 'source' already exists

**Comment by ob-stripe** [comment] 2018-12-05 08:50
Hi @Piachu91, thanks for the report. This issue is a duplicate of #648. See my comment here: https://github.com/stripe/stripe-dotnet/issues/648#issuecomment-431957733.

**Closed by ob-stripe** 2018-12-05 08:50 UTC
