### ISSUE TITLE
Which is the best place to set the Stripe API Key in my .net core app, i need to avoid setting the key everytime

### ISSUE THREAD

**Issue by sarvabowmen** [stripe/stripe-dotnet#1681] opened 2019-06-26 12:00 UTC
I am developing an app and using stripe.net for payment gateway integration, i want to set the API key from azure key vault into the Stripe client which i am using. I want to set in my app once for all, as it will be the same for all the users across the app, to avoid getting the key from azure.

Which is the best place to set the stripe secret key from .net app?

Right now i have a service called StripeService.cs

```c#
public StripeService(ISecretSettings secretSettings)
		{
			_secretSettings = secretSettings;
			StripeConfiguration.SetApiKey(_secretSettings.GetStripeSecret().GetAwaiter().GetResult());
			_customerService = new CustomerService();
			_cardService = new CardService();
		}
```

This code 
`_secretSettings.GetStripeSecret().GetAwaiter().GetResult()` will try to get the key from AzureKeyVault

**Comment by ob-stripe** [comment] 2019-06-26 17:04
Hi @sarvabowmen. We don't have specific recommendations for storing your secret API key since it would be very difficult to provide good one-size-fits-all advice for this. That said, using [Azure Key Vault](https://docs.microsoft.com/en-us/azure/key-vault/key-vault-whatis) for this sounds great to me -- they explicitly list API keys as one of the use cases it's meant to solve.

If you're asking where in your own app you should set the API key, in most cases you would want to:
- set the global API key (via `Stripe.StripeConfiguration.ApiKey = ...`) once, on startup / initialization
- if needed, you can then override the global API key on a per-request basis by creating a `RequestOptions` instance with the `ApiKey` property set to the key you want to use for that request, and pass the `RequestOptions` instance as the last argument:
```c#
var requestOptions = new RequestOptions { ApiKey = "sk_..." };
// The following request will use the API key from requestOptions instead of the global one
var cards = cardService.List("cus_123", null, requestOptions);
```

This should rarely be necessary, but you can also set the API key for a specific service, by creating a custom `StripeClient` instance and passing it to the service constructor:
```c#
var client = new StripeClient("sk_...");
// Requests sent by this service will use the API key from the client instead of the one in StripeConfiguration.ApiKey
var cardService = new CardService(client);
```

Hope this helped! I'm closing the issue since this is not a bug or a feature request for the library, and GitHub issues are not a support channel. If you have followup questions, please reach out to Stripe's support at https://support.stripe.com/email.

**Closed by ob-stripe** 2019-06-26 17:04 UTC
