### ISSUE TITLE
Unable to expand `PaymentIntent` properties

### ISSUE THREAD

**Issue by StanislavChankov** [stripe/stripe-dotnet#2133] opened 2020-07-23 20:52 UTC
OS version: Windows 10 Pro - 1903
.NET Version: .NET Core 3.1

I am unable to expand any of the `PaymentIntent` properties. I want to expand the `invoice` property, I have tried with customer as well, but none of them works.
```
var options = new PaymentIntentCreateOptions
{
                Amount = 100,
                Currency = "usd",
               Expand = new List<string> { "invoice", "customer" },
}

            options.AddExpand("invoice");
            options.AddExpand("customer");
```

using `AddExpand()` should be enough to expand the property as per documentation, but I have tried with assigning a list of the same properties to `Expand` propery. In both cases the properties `invoice`, `invoiceId`, `customer`, `customerId` are `null`.
Am I doing something wrong or `PaymentIntentCreateOptions` are not working as expected?

**Comment by remi-stripe** [comment] 2020-07-23 21:22
@StanislavChankov This should just work and expand the object, assuming that there is one associated. Your code is creating a PaymentIntent directly but not assigning a customer id, so there's nothing to expand in this case. If you passed `Customer = "cus_123"` then we will automatically expand that Customer back on the response. You can't pass `Invoice`, in that case you'd create an invoice (or a subscription) and that would control the payment intent.

I'm going to close this out as it's not a bug with the library itself and more a question about the API. Please reach out to our support team if you need more details: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-07-23 21:22 UTC
