### ISSUE TITLE
sepa debit call fails 

### ISSUE THREAD

**Issue by dolphinsd** [stripe/stripe-dotnet#1764] opened 2019-08-25 01:16 UTC
Using latest version of stripe lib v28.5.0 in net.core 2.1

call to create sepa debit source fails:
```c#
  var options = new SourceCreateOptions
                    {
                        Type = SourceType.SepaDebit,
                        Currency = account.Currency,
Owner = "email@email.com"
                    };
                   
                    options.SepaDebit = new SourceSepaDebitCreateOptions();
                    options.SepaDebit.Iban = account.AccountNumber;

 var service = new SourceService();
                    Source source = await service.CreateAsync(options);`

{
  "error": {
    "message": "The type `sepa_debit` is not a valid source type.",
    "param": "type",
    "type": "invalid_request_error"
  }
}
```

**Comment by ob-stripe** [comment] 2019-08-25 01:25
Hi @dolphinsd. This sounds like an issue with the API rather than with the Stripe.net library.

Note that SEPA Direct Debit is not available on all Stripe accounts:
> Before you can accept SEPA Direct Debit payments, your Stripe account needs to have regularly processed card payments for 30 days. SEPA Direct Debit payments are also subject to processing volume limits, and payments can fail if you exceed your limits. If you are a new customer or plan to process a high volume of transactions, please [get in touch](https://support.stripe.com/contact) to request a review.

(https://stripe.com/docs/sources/sepa-debit)

I recommend you reach to Stripe's support at https://support.stripe.com/contact to clarify whether your account is eligible for SEPA DD or not.

Closing, but feel free to reply if you believe this is actually a bug with the client library.

**Closed by ob-stripe** 2019-08-25 01:25 UTC

**Comment by dolphinsd** [comment] 2019-08-25 01:29
@ob-stripe , thanks, it would be developer friendly to provide test api keys for SEPA testing without jumping the hoops.

**Comment by ennisa-ire** [comment] 2019-09-16 19:42
@dolphinsd What was the resolution to this in the end?

**Comment by RensTillmann** [comment] 2019-11-30 21:10
I am having same problem, contacted support meanwhile. However it doesn't make sense that you can't test it out. They should state this more clearly in the documentation, I planned working on this these days, and now I am stuck. I think there should always be a "sandbox" option available how else could we possible test our nice code(s) :)

**Comment by remi-stripe** [comment] 2019-11-30 21:17
The problem is that if it worked in Test mode with no warning then it'd break when you go live and did not know you need to get access which is a worse experience. If you reach out to our support team, they can help you get access: https://support.stripe.com/contact
