### ISSUE TITLE
Unrecognized request URL (POST: /v1/payment_intents/)

### ISSUE THREAD

**Issue by Mascalalox** [stripe/stripe-dotnet#1827] opened 2019-10-29 12:28 UTC
Im having this error when people try to pay via stripe, what can i do? the json error is this:

> {
  "error": {
    "message": "Unrecognized request URL (POST: /v1/payment_intents/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.",
    "type": "invalid_request_error"
  }
}

>

**Comment by remi-stripe** [comment] 2019-10-29 15:15
@Mascalalox This error indicates that you are likely trying to update a PaymentIntent but when you pass the id as a parameter, that id is not `pi_123` and likely null or an empty string.

I'd recommend looking at your code and printing the id of the PaymentIntent you are trying to update to see if it's set properly

**Comment by Mascalalox** [comment] 2019-10-29 15:22
And where can i see it?

**Comment by remi-stripe** [comment] 2019-10-29 15:48
@Mascalalox That would be specific to your code. Somewhere you must be doing something like this:

```
var paymentIntentId = "";

var options = new PaymentIntentUpdateOptions
{
 // what you're changing
};
var service = new PaymentIntentService();
service.Update(paymentIntentId, options);
```

You should be able to find this code and add logs or do some debugging to confirm that the id of the PaymentIntent, which is the first argument, is set properly.

**Comment by Mascalalox** [comment] 2019-10-29 16:09
I dont see anything like the code that you posted on wordpress, i have looking for on the side of woocommerce code, but nothing

**Comment by remi-stripe** [comment] 2019-10-29 16:16
@Mascalalox Wordpress and Woocommerce are written in PHP not C#/.NET but you were asking on the stripe-dotnet library.

In PHP the code would be around \Stripe\PaymentIntent::` somewhere in your codebase. If you're using a third-party plugin you should be talking to them directly as they would have written the code you're using.

This is an integration problem and not a bug with the stripe-dotnet library so I'm going to close this issue. If you need further help, don't hesitate to talk to our support team directly: https://support.stripe.com/contact

**Closed by remi-stripe** 2019-10-29 16:16 UTC
