### ISSUE TITLE
Exception thrown when creating Direct Charges but Payment still created in Stripe.

### ISSUE THREAD

**Issue by mos-ie** [stripe/stripe-dotnet#1833] opened 2019-11-05 09:20 UTC
We are trying to implement Direct Charges on Connected accounts using the Stripe-Account header authentication as per the Stripe docs: `_requestOptions.StripeAccount = user.StripeCustomerId`

Using the above we get the following exception: : “The provided key ‘SK_test**********’ does not have access to account ‘cus_FsCt1jCiEJkmZx’ (or that account does not exist). Application access may have been revoked.”

However the Payment is created in Stripe: 
 
![image](https://user-images.githubusercontent.com/2778940/68194663-514df780-ffad-11e9-8fae-f9183b479d44.png)

Is this expected behaviour in stripe-dotnet? I recall previous issues I logged where something similar happened: https://github.com/stripe/stripe-dotnet/issues/1784#event-2629629924

**Comment by karlr-stripe** [comment] 2019-11-05 12:09
Hi there — the StripeAccount option should be the ID of a Stripe Account, a string like `acct_xxx` that represents a Stripe account that can process charges , and _not_  a Customer which has an ID like `cus_xxx` that represents a cardholder who is charged, which is why you get the error as you're not passing the right kind of argument. A direct charge is processing a charges using another Stripe account that has connected itself to yours, like the ones seen in your [dashboard](https://dashboard.stripe.com/test/connect/accounts/overview). 

I'm closing this issue as it's not a bug with stripe-dotnet itself — I'd suggest following up with our support team at https://support.stripe.com/email to understand more about Connect and Direct Charges.

**Closed by karlr-stripe** 2019-11-05 12:09 UTC

**Comment by mos-ie** [comment] 2019-11-06 13:09
Hey there, thanks for clarifying. Would you be able to help with the following error?

![image](https://user-images.githubusercontent.com/2778940/68300589-ffcd6780-0095-11ea-9df9-193455cf0606.png)

- Platform secret key is set once globally on application startup

- we are using Stripe-Header auth on a per request basis, and it's set to the ID of the Connected account to whom we want to perform the Direct Charge on

- The Payment Method in the exception is definitely related to a Customer in Stripe

What does platform-owned Payment Method mean?

I have reach out to Stripe support but can never get any technical support unfortunately!

**Comment by paulasjes-stripe** [comment] 2019-11-06 13:17
Hi @mos-ie, "No such..." errors are usually caused by either a mismatch in API keys (e.g. using a mixture of your test plus live keys) or by trying to access objects that exist on a different account (e.g. trying to perform an operation from your platform account on an object that was created on a connected account).

In this case it looks like you're trying to perform an action on behalf of a connected account, but the PaymentMethod was created on your platform account. You can clone the PaymentMethod to your connected account to make this work as you'd expect: https://stripe.com/docs/connect/cloning-saved-payment-methods

**Comment by mos-ie** [comment] 2019-11-06 13:21
Hey there, thanks for the quick response. So what you're saying is the PaymentMethod is linked to a Customer who linked to our platform account, and not the connected account to whom we want to create the direct charge on?

**Comment by paulasjes-stripe** [comment] 2019-11-06 13:25
Correct, the PaymentMethod (and customer) exists on your platform account but you're trying to use it to perform an action on the connected account, where it doesn't exist. To create a direct charge with this PaymentMethod, you'll need to clone it to the connected account first.

**Comment by mos-ie** [comment] 2019-11-06 13:26
Okay, thanks for this - I would have never figured this without asking here!
