### ISSUE TITLE
Inexistent event type invoiceitem.updated

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#2763] opened 2023-09-07 22:55 UTC
### Describe the bug

Was the invoiceitem.updated removed in 2023-08-16?

We get an error when creating the webhook endpoint: ": 'You do not have access to the event types: invoiceitem.updated.'"

Yet, it is still available at https://github.com/stripe/stripe-dotnet/blob/e47583a1ac7986ad55abd60f4e5b4ca32dab4665/src/Stripe.net/Constants/Events.cs#L584

### To Reproduce

Create a new webhook endpoint with invoiceitem.updated

### Expected behavior

I guess it should be removed from the events class.

### OS

n/a

### .NET version

7

### Library version

stripe-dotnet 42.4.0

### API version

2023-08-16

**Comment by remi-stripe** [comment] 2023-09-08 06:02
@clement911 We are deprecating the `invoiceitem.updated` Event. The product team behind this has been planning this change for a few months and reaching out to all developers that were listening to that Event. If you never got the email I'd recommend reaching out to our support team to help directly: https://support.stripe.com/contact

I'm going to close this issue since it's not a bug with the library itself and our support team can help further!

**Closed** 2023-09-08 06:03 UTC
Labels: bug

**Comment by remi-stripe** [comment] 2023-09-08 08:59
Quick update: we do plan to remove it from the library but it will be in the next major which will take a while unfortunately
