### ISSUE TITLE
Seems like EventUtility.ParseEvent not working.

### ISSUE THREAD

**Issue by ivanromakh** [stripe/stripe-dotnet#1502] opened 2019-02-06 11:04 UTC
EventUtility.ParseEvent working good in test mode from Stripe
But there is weard variable names request which is null in test mode.
![image](https://user-images.githubusercontent.com/18567511/52337143-82de6600-2a0f-11e9-9f1c-d61e3fb13d7e.png)

But if I used real webhook event this variable throwing error during serialization.

![image](https://user-images.githubusercontent.com/18567511/52337197-ae615080-2a0f-11e9-97c8-054da386b3c4.png)

![image](https://user-images.githubusercontent.com/18567511/52337217-bb7e3f80-2a0f-11e9-95cd-9b0a875c048f.png)

If there is another function which can serialize webhook event please tell me about it:)

I read some clossed issues and see that request was something like this
"request": {
    "id": "req_v2abI45LNL6wAo",
    "idempotency_key": null
  },

but now it is just a string like this "request": "req_v2abI45LNL6wAo"

**Comment by ob-stripe** [comment] 2019-02-06 11:14
Hi @ivanromakh. The issue is that your account's default API version is older than [2017-05-25](https://stripe.com/docs/upgrades#2017-05-25), and you're using a version of Stripe.net that is pinned to a more recent API version. As a result, Stripe.net is unable to deserialize the event because it expects `request` to be a hash instead of a string.

In the latest major release of Stripe.net (22.0), we updated the library to handle this particular issue (cf. #1450). However, note that by default, the library will raise an exception if the API version of the event (i.e. your account's default API version) doesn't match the API version that Stripe.net is pinned to (which, for Stripe.net 22.0, is the latest API version, [2018-11-08](https://stripe.com/docs/upgrades#2018-11-08)).

You can disable this by passing `throwOnApiVersionMismatch: false` to the `ParseEvent()` method, but it is recommended that you instead upgrade your account's API version to ensure the event are formatted with the same API version as Stripe.net expects.

You can find more information in the [migration guide for v22](https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v22#event-deserialization-with-eventutilityconstructevent--eventutilityparseevent).

(Not directly related to your issue, but I also recommend that you use the `ConstructEvent()` method instead of `ParseEvent()` in order to [verify webhook signatures](https://stripe.com/docs/webhooks/signatures).)

I'm closing this issue, but feel free to reply if needed.

**Closed by ob-stripe** 2019-02-06 11:14 UTC

**Comment by ivanromakh** [comment] 2019-02-06 11:16
@ob-stripe  Thanks a lot:)
