### ISSUE TITLE
Missing product description when using Checkout Session generated at backend

### ISSUE THREAD

**Issue by bemnlam** [stripe/stripe-dotnet#2275] opened 2021-01-20 11:17 UTC
Recently I need to build a simple checkout application and allow users to enter promotion code. In the .NET Core web app, a checkout session is created using the following `SessionCreateOptions`:

```c#
var stripePriceId = "price_xxxxx";
var s = new Stripe.Checkout.SessionCreateOptions
{
    LineItems = new List<Stripe.Checkout.SessionLineItemOptions>
    {
        new Stripe.Checkout.SessionLineItemOptions
        {
            Price = stripePriceId,
            Quantity = 1
        }
    },
    Mode = "payment",
    SuccessUrl = $"https://localhost:5001/success/?stirpePriceId={ stripePriceId }",
    CancelUrl = $"https://localhost:5001/?stirpePriceId={ stripePriceId }",
    PaymentMethodTypes = new List<string> { "card" },
    // AllowPromotionCodes = true
};
```

(I tried to create the session with or without `AllowPromotionCodes`, it gives me the same result.)

### Actual Result
The library did return a checkout session ID and I can make use of the ID to do the checkout. However, **in the corresponding `charge.succeeded` event, the `description` field is `null`.**

I also tried to use the js checkout code snippet (from Checkout snippet generator). In this case, the corresponding `charge.succeeded` object contains a `description` like *1x {my product name}*.

### Expected Result
The `charge` object should gives the `description` like  *1x {my product name}* instead of having `null` when using the backend-generated session ID.

### Additional information
I've created a simple .NET Core web app to illustrate the this issue: https://github.com/bemnlam/stripe-checkout-demo

### Environment
- Stripe.net library: **39.32.0**
- OS version: **macOS 10.15.7**
- .NET Core version: **3.1.402**

(I am not sure if this is a problem of the .NET version library only or it happens across all the libraries. I found this issue when  using .NET library so I report it here 🙏)

**Comment by remi-stripe** [comment] 2021-01-20 16:52
@bemnlam Thanks for reaching out! This is not really a question about the library itself and is more a "product question" about how to use Checkout in your code. Since Github issues should be limited to bugs within the library itself I'm going to close this out. For questions like this I recommend reaching out to our support team in https://support.stripe.com/contact or chat with developers on IRC on Freenode in #stripe

To unblock you though, this is expected behaviour today. While your idea to make the description automatically match the line item, what would you expect when you have 2 line items, or even 10. The description on the Charge is separate from the Session and its line items. As a developer though you can directly control this in the API by setting `payment_intent_data[description]` which will set the description on the `PaymentIntent` associated with that Session and also automatically set it on the underlying `Charge` that will be associated with that `PaymentIntent`. This is documented [here](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-description).

So in your code you would do this:

```
var stripePriceId = "price_xxxxx";
var s = new Stripe.Checkout.SessionCreateOptions
{
    LineItems = new List<Stripe.Checkout.SessionLineItemOptions>
    {
        new Stripe.Checkout.SessionLineItemOptions
        {
            Price = stripePriceId,
            Quantity = 1
        }
    },
    Mode = "payment",
    SuccessUrl = $"https://localhost:5001/success/?stirpePriceId={ stripePriceId }",
    CancelUrl = $"https://localhost:5001/?stirpePriceId={ stripePriceId }",
    PaymentMethodTypes = new List<string> { "card" },
    PaymentIntentData = new Stripe.Checkout.SessionPaymentIntentDataOptions
    {
      Description = 'My charge description',
    },
    // AllowPromotionCodes = true
};
```

**Closed by remi-stripe** 2021-01-20 16:52 UTC
