### ISSUE TITLE
Subscription entity has a broken items spec

### ISSUE THREAD

**Issue by mfferreira** [stripe/stripe-dotnet#2213] opened 2020-10-02 13:26 UTC
The current .NET SDK seems to have a broken Subscription entity definition.

Looking at:
https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/Subscriptions/Subscription.cs#L253
```
        /// <summary>
        /// List of subscription items, each with an attached price.
        /// </summary>
        [JsonProperty("items")]
        public StripeList<SubscriptionItem> Items { get; set; }

        #region Expandable LatestInvoice
```
`items` is defined as a list of `SubscriptionItem`.

But this is definitely not the case, as the Stripe api responds with something like this:
```
  "items": {
    "object": "list",
    "data": [
      {
        "id": "",
        "object": "subscription_item",
        "billing_thresholds": null,
        "created": 1601565716,
        "metadata": {},
        "plan": {},
        "price": {},
          "tiers": null,
          "tiers_mode": null,
          "transform_quantity": null,
          "type": "recurring",
          "unit_amount": 2000,
          "unit_amount_decimal": 2000
        },
        "quantity": 1,
        "subscription": "",
        "tax_rates": []
      }
    ],
    "has_more": false,
    "url": "/v1/subscription_items?subscription="
  },
```

This iis specially critical, because we generate our own openapi spec using this entities.

--

Stripe: 39.10.0
.NET core: 3.1
OS: Linux Amazon Linux 2

--

**Comment by remi-stripe** [comment] 2020-10-02 15:29
@mfferreira The JSON you shared maps what we have in the Subscription class so I don't understand what's not working for you. The JSON says that `items` is a Stripe list of `SubscriptionItem` resources. And in `Subscription` it says `StripeList<SubscriptionItem>`. `StripeList` is not the .NET `List` class`. It's our own internal resource that has our API abstraction for lists and it is defined in the code [here](https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/StripeList.cs)

**Comment by mfferreira** [comment] 2020-10-05 08:34
Let me check this with the team, and I'll follow up.

**Comment by ravtakhar** [comment] 2020-11-17 02:37
Running into the same issue. Subscriptions is pulling back no data

**Comment by remi-stripe** [comment] 2020-11-17 04:29
@ravtakhar Could you provide more specific details about the issue(s) you are encountering? We were not able to gather more information in this thread and it's been over a month so it's unlikely to be a problem with the library itself.

**Comment by ravtakhar** [comment] 2020-11-17 14:53
All I am doing is loading the customer record and the subscriptions are coming back as a null array. When loading the customer record via ID on version 32 all of the subscriptions are populated.

**Comment by remi-stripe** [comment] 2020-11-17 16:29
@ravtakhar This is a pretty different question in that case. And it's not a bug with the library or the code. The `Subscriptions` list on the `Customer` resource is not returned by default since the latest API version [2020-08-27](https://stripe.com/docs/upgrades#2020-08-27). It's a property that is "includable" which is covered in our docs [here](https://stripe.com/docs/expand#includable-properties) so if you want to access it when retrieving a customer you need to expand that property by adding `options.AddExpand("subscriptions");` though we recommend simply using the List Subscriptions [API](https://stripe.com/docs/api/subscriptions/list) separately.

I'm going to close this out since it's more a support question about our product and the original ask was not followed up on either. Hopefully it unblocks you but if you have more questions, please contact our support team: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-11-17 16:29 UTC
