### ISSUE TITLE
"No such token" error when using Alipay Source

### ISSUE THREAD

**Issue by SimonChris** [stripe/stripe-dotnet#1258] opened 2018-08-23 15:40 UTC
After creating and validating an Alipay source in test mode, I attempt to create a charge, setting SourceTokenOrExistingSourceId to the Id of the Alipay source. This fails with a "No such token" error, even though I just retrieved the source from the StripeSourceService.

I am certain that my public and secret Api keys are correct, since I can successfully make test charges using test cards. The status of the source is "chargeable".

Am I doing something wrong? The "No such token" error seems weird, since I am using an Alipay source and not a card token. However, SourceTokenOrExistingSourceId seems to be the only way to set the source id of the charge.

**Comment by remi-stripe** [comment] 2018-08-23 15:46
@SimonChris Do you have a bit more details about the error? I'm fairly sure it's not a bug with the library itself. This is an API error indicating that you are trying to charge a source that does not exist, at least in that Stripe account.

If you could provide the request id (req_XXXX) I can confirm quickly.

**Comment by SimonChris** [comment] 2018-08-23 15:50
req_Y4ZRGay2C80ca1

**Comment by SimonChris** [comment] 2018-08-23 15:52
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such token: src_1D2KwMBHCi9Jck4sAfZnfKzu",
    "param": "source",
    "type": "invalid_request_error"
  }
}

What puzzles me is that I can retrieve the source through StripeSourceService, so it clearly does exist. All my services use the same Api Key.

**Comment by remi-stripe** [comment] 2018-08-23 15:55
Okay so the error is in your code and not the library. The source exists on the *platform* but you are trying to charge that source on the connected account which can not work. You have to change your integration to properly create the source directly on the connected account instead as documented here: https://stripe.com/docs/sources/connect#creating-direct-charges

Going to close this out as it's not a bug with the library but you can talk to our support team directly for any follow up questions: https://support.stripe.com/email

**Closed by remi-stripe** 2018-08-23 15:55 UTC

**Comment by SimonChris** [comment] 2018-08-23 16:42
Thank you very much for your quick reply :).
