### ISSUE TITLE
Cannot install Stripe.net on PCL side

### ISSUE THREAD

**Issue by Emixam23** [stripe/stripe-dotnet#999] opened 2017-08-31 17:25 UTC
Hi,

I have to finish a project as soon as possible in Xamarin (Android, iOS, UWP). Stripe is my last thing to integrate, however, I can't find the way to install it in the PCL part. I could install it for Xamarin.Android & Xamarin.iOS.

The error thrown from the PCL part at the NuGet installation is the following:

    Attempting to gather dependency information for package 'Stripe.net.10.4.0' with respect to project 'PROJECT', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
      GET https://api.nuget.org/v3/registration3-gz-semver2/stripe.net/index.json
      OK https://api.nuget.org/v3/registration3-gz-semver2/stripe.net/index.json 289ms
      GET https://api.nuget.org/v3/registration3-gz-semver2/stripe.net/page/7.7.0/10.4.0.json
      OK https://api.nuget.org/v3/registration3-gz-semver2/stripe.net/page/7.7.0/10.4.0.json 531ms
    Total number of results gathered : 20
    Gathering dependency information took 826.02 ms
    Summary of time taken to gather dependencies per source :
    https://api.nuget.org/v3/index.json -   825.53 ms
    Attempting to resolve dependencies for package 'Stripe.net.10.4.0' with DependencyBehavior 'Lowest'
    Resolving dependency information took 0 ms
    Resolving actions to install package 'Stripe.net.10.4.0'
    Resolved actions to install package 'Stripe.net.10.4.0'
    Found package 'Stripe.net 10.4.0' in '/xxx/PROJECT/packages'.
    For adding package 'Stripe.net.10.4.0' to project 'PROJECT' that targets 'portable45-net45+win8+wpa81'.
    Install failed.Rolling back...
    Package 'Stripe.net.10.4.0' does not exist in project 'PROJECT'
    Executing nuget actions took 46.19 ms
    Could not install package 'Stripe.net 10.4.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I tried to change the profile to 259 without success... There is my packages :

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="Microsoft.Bcl" version="1.1.10" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Newtonsoft.Json" version="10.0.3" targetFramework="portable45-net45+win8+wpa81" />
      <package id="PCLCrypto" version="2.0.147" targetFramework="portable45-net45+win8+wpa81" />
      <package id="PCLStorage" version="1.0.2" targetFramework="portable45-net45+win8+wpa81" />
      <package id="PInvoke.BCrypt" version="0.5.97" targetFramework="portable45-net45+win8+wpa81" />
      <package id="PInvoke.Kernel32" version="0.5.97" targetFramework="portable45-net45+win8+wpa81" />
      <package id="PInvoke.NCrypt" version="0.5.97" targetFramework="portable45-net45+win8+wpa81" />
      <package id="PInvoke.Windows.Core" version="0.5.97" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Plugin.Permissions" version="2.0.1" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Validation" version="2.4.15" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Xam.Plugin.Connectivity" version="3.0.2" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Xam.Plugin.Geolocator" version="4.0.1" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Xam.Plugin.Media" version="3.0.1" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Xam.Plugin.PushNotification" version="1.2.4" targetFramework="portable45-net45+win8+wpa81" developmentDependency="true" />
      <package id="Xamarin.Auth" version="1.5.0.3" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Xamarin.Forms" version="2.3.4.270" targetFramework="portable45-net45+win8+wpa81" />
      <package id="Xamarin.Forms.Maps" version="2.3.4.270" targetFramework="portable45-net45+win8+wpa81" />
    </packages>

**Comment by jager1000** [comment] 2017-09-05 10:30
Same issue here, using profile 111.

**Comment by Emixam23** [comment] 2017-09-05 11:16
I found a workaround, you have to install it on each sub platform, and use it with (interface). Dependency services..

**Comment by ormedo** [comment] 2017-09-05 11:31
I use this workaround in my project

**Comment by Emixam23** [comment] 2017-09-05 11:34
Does it work well? Can you provide the workaround in a public repo or an example. I haven't moved forward yet but I need to convert a credit card to a token

**Comment by ormedo** [comment] 2017-09-05 11:51
I use this workaround in mi production project

**Comment by jager1000** [comment] 2017-09-05 12:12
@Emixam23 Omg you would be my hero if you had a project or something I can use to help me get this done. Been stuck for days. I found a few other threads around the net that try to help but they are usually outdated or don't work.

**Comment by anelder-stripe** [comment] 2017-09-06 18:24
Hey @Emixam23 (and everyone else),

I think this is a fair complaint, but I don't know that we'd ever really get rid of that library though.  It's really the only one available that allows us to support the webhook signatures feature.  We'd likely need to build a separate DLL that excluded that feature entirely.  I don't know that we'd do that though in the long run.  I'm not convinced PCL support is a huge priority for the library, but I could likely be swayed away from my ignorance.

cc: @brandur-stripe + @fred-stripe - your thoughts here?

**Comment by Emixam23** [comment] 2017-09-06 18:44
I'm using the package at the moment, and I can't even find the way to create a card and generate a token from it...

**Comment by jager1000** [comment] 2017-09-06 20:48
So does anyone have a walkthrough on integrating stripe into a Xamarin forms project start to end? Would be well welcome, this is my first XF and commerce app.

**Comment by ormedo** [comment] 2017-09-07 06:18
I Only have to create a charge in my project, but you cant export the principes to your project.

Forms Interfaces.

`public interface ICustomStripeService
    {
        Task<InforAutosStripeCharge> MakePayment(StripeCardInfo cardInfo, double Amount);
    }`

Andriod Implementation
async Task<InforAutosStripeCharge> ICustomStripeService.MakePayment(StripeCardInfo cardInfo, double amount)
        {
            InforAutosStripeCharge result = new InforAutosStripeCharge();
            try
            {
                var myCharge = new StripeChargeCreateOptions();
                var myToken = new StripeTokenCreateOptions();
                myToken.Card = new StripeCreditCardOptions()
                {
                    Number = cardInfo.CardNumber,
                    ExpirationMonth = cardInfo.Month,
                    ExpirationYear = cardInfo.Year,
                    Cvc = cardInfo.CCV
                };
                // Stripe amount transformation from double with 2 decimals
                myCharge.Amount = Int32.Parse((amount * Int32.Parse("100")).ToString());
                myCharge.Currency = "EUR";

                var chargeService = new StripeChargeService(API_KEY);
                var tokenService = new StripeTokenService(API_KEY);
                var token = tokenService.Create(myToken);
                myCharge.SourceTokenOrExistingSourceId = token.Id;
                StripeCharge stripeCharge = await chargeService.CreateAsync(myCharge);
                result.FailureMessage = stripeCharge.FailureMessage;
                result.IsPaid = stripeCharge.Paid;
                result.ID = stripeCharge.Id;
            }
            catch (System.Exception ex )
            {
                result.FailureMessage = ex.Message;
            }
           
            return result;
        }`

And the Same on iOS.

Hope that this code will help you guys

**Comment by Emixam23** [comment] 2017-09-07 07:29
Hi ! 

It doesn't work for me :/

`....../Droid/Sources/DependencyServices/StripeServices.cs(90,90): Error CS0246: The type or namespace name 'StripeCardInfo' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (PROJECT.Droid)`

`....../Droid/Sources/DependencyServices/StripeServices.cs(54,54): Error CS0246: The type or namespace name 'InforAutosStripeCharge' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (PROJECT.Droid)`

**Comment by ob-stripe** [comment] 2017-10-19 18:11
Closing this issue as a duplicate of https://github.com/stripe/stripe-dotnet/issues/965.

**Closed by ob-stripe** 2017-10-19 18:11 UTC
