### ISSUE TITLE
StripePlan.cs missing Name property

### ISSUE THREAD

**Issue by madsbrydegaard** [stripe/stripe-dotnet#1111] opened 2018-02-22 09:28 UTC
After updating to vs. 13+ StripePlan.cs does not have Name property any more.
The Stripe API still expose the name so why remove it from object?

**Comment by ob-stripe** [comment] 2018-02-22 09:30
@madsbrydegaard Stripe.net is tied to a specific API version. The `name` property was removed in the latest API version (cf. https://stripe.com/docs/upgrades#2018-02-05).

I'm closing this issue as this is not a bug with the library. If you have further questions you should reach out to support at https://support.stripe.com/email.

**Closed by ob-stripe** 2018-02-22 09:30 UTC

**Comment by madsbrydegaard** [comment] 2018-02-22 09:53
thanks I wasnt aware...

--
Venlig hilsen / Kind regards
Mads Brydegaard
Tlf. (+45) 2868 1707

2018-02-22 10:30 GMT+01:00 Olivier Bellone <notifications@github.com>:
