### ISSUE TITLE
Uploading stripe.net 37.27.0.0 with .netCore version 3.1 api on AWS docker gives file not found error

### ISSUE THREAD

**Issue by HaseebIftikhar5275501** [stripe/stripe-dotnet#2173] opened 2020-08-09 18:14 UTC
Hi,

I have an API in .netCore 3.1 and I used stripe.net dll version 37.27.0.0 in my project. Everything is working fine on local host. When I upload the API release to AWS Docker container with same stripe.net dll version 37.27.0.0, my API stopped working and give me error in log as below:

Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2020-08-09 22:51:20 Could not load file or assembly 'Stripe.net, Version=37.27.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Any help would be highly appreciated. Where I am doing wrong.

Regards

**Comment by HaseebIftikhar5275501** [comment] 2020-08-09 18:21
Someone mentioned the solution as below [https://github.com/stripe/stripe-dotnet/issues/1045](url)
"Here is the solution that worked for me.

Download Stripe.net from github and load Stripe.net.sln in Visual Studio
Compile Stripe.net project (don't compile tests)
Obtain stripe.net.dll from bin\Release\net45 folder
In your actual project, remove reference to Stripe.net and replace the file and re-add reference
This issue can be closed

Edit: doh! forgot to mention at step 2 that you need edit the project properties and use the "Sign the assembly" option"

Why do i need to do this step and how. What would be the signing key?

**Comment by ctrudeau-stripe** [comment] 2020-08-11 18:40
Hello @HaseebIftikhar5275501, 

Most likely this is not a bug with Stripe dotnet. It looks like something is going wrong with the deploy and upload to AWS. I'm going to close this out as it's not a bug with the library itself and more a question about deployment. Please reach out to our support team if you need more details: https://support.stripe.com/contact

**Closed by ctrudeau-stripe** 2020-08-11 18:40 UTC
