### ISSUE TITLE
httpbase doesnt not have a reference for body

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [stripe/stripe-dotnet#2092] opened 2020-06-30 08:08 UTC
Hi I am trying to add a weebhook to listen to the post payment details.

And using the docs provided, I get the following error. I am using a .net web api application to provide the server side.

also the payment intent is being read by the api key right?

so what is the purpose of endpointSecret ?

**Comment by paulasjes-stripe** [comment] 2020-06-30 08:29
Hi there, did you mean to attach an error message here? 

The purpose of a webhook signing secret is to protect you against [replay attacks](https://stripe.com/docs/webhooks/signatures#replay-attacks). It's not required but highly recommended.

**Comment by JERINJACOBCHERIAN** [comment] 2020-06-30 10:32
yes I get the error "httpbase doesnt not have a reference for body"

**Comment by remi-stripe** [comment] 2020-06-30 16:46
@JERINJACOBCHERIAN This must be an issue with your code and your current environment. You might need to tweak your code to read the raw post body we send you depending on how your framework is configuring this.

I'm going to close this issue because it's not a bug with stripe-dotnet itself and more a coding question. You should reach out to our support team directly and provide details about your code and your environment and they can help: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-06-30 16:46 UTC
