### ISSUE TITLE
Error on Creating Subscription 

### ISSUE THREAD

**Issue by RS-Roshi** [stripe/stripe-dotnet#2228] opened 2020-10-16 14:01 UTC
Getting Error while creating subscription againt a price that is Non Recurring 
**The price specified is set to `type=one_time` but this field only accepts prices with `type=recurring`.**

ASP.Net Core 3.1 
Angular 10
Stripe 39.15.0.0

```
public async Task CreateStripeSubscription(JosephLms.Models.Entities.Subscription _subscription)
        {
            var productService = new ProductService();
            var priceService = new PriceService();

            var products = await productService.ListAsync();
            var prices = await priceService.ListAsync();
            if (!products.Any(x => x.Name.Equals(_subscription.Name, StringComparison.InvariantCultureIgnoreCase)))
            {
                var productOptions = new ProductCreateOptions
                {
                    Name = _subscription.Name
                };
                var newProduct = await productService.CreateAsync(productOptions);
                _subscription.StripeSubscriptionId = newProduct.Id;

                if (!prices.Any(x => x.Nickname.Equals(_subscription.Name)))
                {
                    var priceObj = new PriceCreateOptions
                    {
                        Nickname = _subscription.Name,
                        UnitAmount = (long)(_subscription.Price * 100),  // to convert dollars into cents
                        Product = _subscription.StripeSubscriptionId,
                        Currency = "usd",
                        
                    };
                    if (_subscription.IsRecuring)
                    {

                        priceObj.Recurring = new PriceRecurringOptions
                        {
                            Interval = _subscription.BillingCyle
                        };
                    }
                    var newPrice = await priceService.CreateAsync(priceObj);
                    _subscription.StripeSubscriptionPriceId = newPrice.Id;
                }


            }



        }


        public async Task<string> CreateOrganizationSubscriptionId(RegisterOrganizationDto model, string _StripeSubscriptionPriceId)
        {

            var _customerService = new CustomerService();
            var _subscriptionService = new SubscriptionService();
            var response = await _customerService.CreateAsync(new CustomerCreateOptions
            {
                Email = model.Email,
                Name = model.FirstName + ' ' + model.LastName,
                Source = model.StripeToken,
                
            });

            // Create Subscription
            _subscriptionService.Create(new SubscriptionCreateOptions
            {
                Customer = response.Id,
                Items = new List<SubscriptionItemOptions>
                {
                    new SubscriptionItemOptions
                    {
                        Price = _StripeSubscriptionPriceId,
                        Quantity = 1,

                    }
                }
            });


            return response.Id;
        }
```

**Comment by remi-stripe** [comment] 2020-10-16 19:07
@RS-Roshi You can not pass one-time prices to a Subscription, that's just not possible. A Subscription's `Items` parameter expects only recurring Prices and nothing else. If you want to charge an extra one-time fee on the first invoice of a subscription you can use `AddInvoiceItems` instead as documented here: https://stripe.com/docs/api/subscriptions/create?lang=dotnet#create_subscription-add_invoice_items

On the other hand, if you want to charge someone say $10 monthly, you need to make sure you create a recurring Price: https://stripe.com/docs/api/prices/create?lang=dotnet#create_price-recurring

I'm going to close this issue as it's not a bug with the stripe-dotnet library and instead it's more a question about how to use the API. Please reach out to our support team instead if you need further help about using the API: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-10-16 19:07 UTC
