### ISSUE TITLE
Stripe 33.7 webhook signature fails with ASP.Net Core 3.1

### ISSUE THREAD

**Issue by ameyasubhedar** [stripe/stripe-dotnet#1853] opened 2019-11-25 23:44 UTC
I have recently migrated the asp.net core 2.2 web projects to asp.net core 3.1. I have also moved to the latest Stripe.NET REST API library 33.7 from NuGet.

**Added a webhook 2019-11-05**  (this is the only version available right now ) in the Stripe Test Environment

![image](https://user-images.githubusercontent.com/13166236/69586986-10884380-0f99-11ea-904b-d5bf0c2a11b6.png)

Here is the End Point in ASP.NEt Core 3.1. The [FromHeader] populates the test stripeSignature correctly as "t=1574725304,v1=5fd9a176bcbd919f93544b7dca5faaf2d0f2ff0ec990af89056e3e6136b9c5e0,v0=50b25c77087b4d1d1b04dc5e1b2c7c1ea000b31b4abccb6e033f7c2ee22d0b54"

```
        [HttpPost]
        public async Task<IActionResult> Index([FromBody] JsonElement body, [FromHeader(Name = "Stripe-Signature")] string stripeSignature)
        {
            if (body.Equals(default(JsonElement)))
            {
                return BadRequest("Request body cannot be null or empty.");
            }

            if (string.IsNullOrEmpty(stripeSignature))
            {
                return BadRequest("Stripe signature is null or empty.");
            }
      
           Stripe.Event stripeEvent = Stripe.EventUtility.ConstructEvent(json, stripeSignature, this._stripeSigningSecret, 300, true);
      }
}
```
The end point is called correctly but the  Stripe.EventUtility.ConstructEvent throws an exception

```
The signature for the webhook is not present in the Stripe-Signature header.
   at Stripe.EventUtility.ConstructEvent(String json, String stripeSignatureHeader, String secret, Int64 tolerance, Int64 utcNow, Boolean throwOnApiVersionMismatch)
   at Stripe.EventUtility.ConstructEvent(String json, String stripeSignatureHeader, String secret, Int64 tolerance, Boolean throwOnApiVersionMismatch)
   at Web.Apis.Organization.V1.Controllers.stripecontroller.Index(JsonElement body, String stripeSignature) in D:\this\PI\WebApps\Source\Web.Apis.Organization\V1\Controllers\StripeController.cs:line 71
```
I have verified the that the **Sigining Secret** is correct

Is 2019-11-05 the correct Webhook endpoint for Stripe 33.7. The Stripe web app take this version by default?

**Comment by remi-stripe** [comment] 2019-11-26 00:02
@ameyasubhedar That is the correct API version for this version of the stripe-dotnet library.

The issue is not a bug with the library itself though so I'm going to close it out. For technical support, you should reach out to our support team directly instead: https://support.stripe.com/contact

Usually though the problem is that your framework/code is parsing the data ahead of time instead of providing the exact raw body you received to the ConstructEvent method. You need to investigate this and make sure that you are not parsing the data and that it's not altered ahead of time.

**Closed by remi-stripe** 2019-11-26 00:02 UTC
