### ISSUE TITLE
Strange object model for Balance

### ISSUE THREAD

**Issue by clement911** [stripe/stripe-dotnet#1969] opened 2020-03-27 17:52 UTC
I find it strange that `Balance.SourceTypes` is modeled as a `Dictionary<string, long>`.

Why not a `SourceTypes` class with 3 properties `BankAccount`, `Card`, `FPX`?

I imagine the idea is to make it extensible for future additional types, but the documentation actually documents this 3 specific fields and not a dynamic list.

It's feels inconsistent with the rest of the model, which is explicit for all objects and properties.

Thoughts?

**Comment by clement911** [comment] 2020-03-27 17:53
Also, it means I have to hard code `"bank_account"` or `"card"` or `"fpx"` in my code to access the correct value.

**Comment by remi-stripe** [comment] 2020-03-27 18:00
@clement911 Thanks for the feedback. Without going to deep into historical decisions, `source_type` was originally supposed to only be for ACH and to be temporary. That was back in 2015 though. We recently did some work towards removing the need to separate the funds for bank account but now FPX also needs a similar feature.

It's something we want to fix but we've been hesitant to make a breaking change in stripe-dotnet to a core API that has been working that way for a while.

I'm planning  a major version soon where I'm doing some renamed in https://github.com/stripe/stripe-dotnet/pull/1961. I could make that rename there but the problem is that we have multiple "secret" balance source types internally and we might add more. The current version of the code makes it a lot easier for developers to handle those.

**Comment by clement911** [comment] 2020-03-27 18:14
I see. Well, that's what major version are for 😄 

So, these secret balances, external apps cannot access them right?

**Comment by remi-stripe** [comment] 2020-03-27 18:14
They can, if they have this feature enabled for example.

**Comment by clement911** [comment] 2020-03-27 18:15
How do we enable that feature?

**Comment by remi-stripe** [comment] 2020-03-27 18:17
It depends on the feature. You might be in a beta, you might be a user with a specific need, you might have access to an historical feature we don't offer anymore because we improved it but still didn't want to break your integration. There are many approaches here but what it boils down to is that with stripe-dotnet especially it's really hard to access fields that are not "officially public" and so for some core resources it is sometimes easier to just do the map of string/X because that makes it flexible for everyone.

I'll definitely add that request to the list of things we should consider changing and it'll likely go in the next major (I've debated that one for a few months internally but we wanted to wait for user-feedback so perfect timing!)

**Comment by clement911** [comment] 2020-03-27 18:21
I see, thanks for the explanation.

As far as 'secret' fields, why not expose a dynamic object or `JToken` on the `StripeResponse` so that it's always possible to dig into the raw json response object if needed?

**Comment by remi-stripe** [comment] 2020-03-27 18:32
We tried something in the past which didn't work well because it broke whenever we did start adding support for the feature officially. You can find more details in the PR from last year https://github.com/stripe/stripe-dotnet/pull/1707

Overall, having to deal with JSON deserialization yourself, especially with stripe-dotnet and our custom settings, is just more annoying than we'd like. It's fine if you use a super-beta feature, but for something as core as "accessing the balance's source type" this feels like pushing it a bit.

**Comment by remi-stripe** [comment] 2020-03-28 01:15
@clement911 Going to close this one out but flagging @ob-stripe opened a PR to give access to the raw JObject after all: https://github.com/stripe/stripe-dotnet/pull/1970

**Closed by remi-stripe** 2020-03-28 01:15 UTC

**Comment by clement911** [comment] 2020-03-28 06:39
> Overall, having to deal with JSON deserialization yourself, especially with stripe-dotnet and our custom settings, is just more annoying than we'd like. It's fine if you use a super-beta feature, but for something as core as "accessing the balance's source type" this feels like pushing it a bit.

For sure, my suggestion to was to keep the static model but also add dynamic access.
So that I can do `balance.Available.SourceTypes.Card` but also `balance.StripeResponse["available"]["source_types"]["mySecretBalanceType"]` if I want/need to.

I think that's what this new PR will allow so hopefully once it's released it means you can also clean up the object model for balance to provide static access to documented source types.

**Comment by clement911** [comment] 2020-03-31 12:45
I would have the same feedback for `charge.fraud_details`, which is implemented as a `Dictionary<string, string>` even though 2 explicit fields are documented.

**Comment by remi-stripe** [comment] 2020-03-31 17:10
Ah nice catch. I'll make a pass in the library to check all other dictionaries that are not metadata to see if I can clean up some more in the next major version!

**Comment by clement911** [comment] 2020-04-01 05:54
Great!

In the near term I'll be literally going through almost every property in the library so I'll keep this kind of feedback coming.

**Comment by remi-stripe** [comment] 2020-04-01 14:20
> In the near term I'll be literally going through almost every property in the library so I'll keep this kind of feedback coming.

Out of curiosity, can you clarify why you would be doing something like this exactly?

**Comment by clement911** [comment] 2020-04-02 06:52
Oh sure.

We are building a Stripe Connect extension that does reporting & analytics.
It will allow Stripe users to install our extension and get in-depth reporting of their Stripe account data.

We want it to be quite comprehensive and we are pulling almost all the data that we can via Stripe.Net into our own database, so that the reports can generated instantly and be flexible.

We are mapping almost every existing field of the API into our own tables and we need to get the data model right. I imagine it's a process similar to the [Sigma schema](https://stripe.com/docs/sigma#schema) behind the scenes.

**Comment by clement911** [comment] 2020-04-10 07:00
According the [Issuing balance docs](https://stripe.com/docs/issuing/funding/balance#track-your-issuing-balance) there should also be an `issuing` field on the `Balance` object.
Issuing is live right?

**Comment by remi-stripe** [comment] 2020-04-10 07:06
Issuing is in between beta and live. The `issuing` balance is not publicly documented yet as you can confirm [here](https://stripe.com/docs/api/balance/balance_object) which is why it's not yet in the libraries, but it's coming soon

**Comment by clement911** [comment] 2020-04-10 07:53
Understood.
