### ISSUE TITLE
Blocking - Unable to round trip Json

### ISSUE THREAD

**Issue by niemyjski** [stripe/stripe-dotnet#1642] opened 2019-06-04 19:10 UTC
Latest .NET release on NuGet... I get the following error when I try to parse an event. I would like to believe that I should be able to copy the response body on the stripe dashboard or calling the api directly and calling ToJson should allow me to parse an event but this is not the case.........

```cs
var client = new Stripe.ChargeService("test");
var charge = await client.GetAsync("id");
string json = charge.ToJson();
```

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Stripe.Infrastructure.EventConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Stripe.net/Infrastructure/JsonConverters/EventConverter.cs:line 83
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Stripe.Mapper`1.MapFromJson(String json, String parentToken, StripeResponse stripeResponse) in /_/src/Stripe.net/Infrastructure/Public/Mapper.cs:line 31
   at Stripe.EventUtility.ParseEvent(String json, Boolean throwOnApiVersionMismatch) in /_/src/Stripe.net/Services/Events/EventUtility.cs:line 19
   ```

**Comment by ob-stripe** [comment] 2019-06-04 20:49
@niemyjski Can you clarify what you're doing exactly? The code you shared is for _serializing_ a charge object, but the exception below can only happen in when _deserializing_ an event object.

**Comment by winzig** [comment] 2019-06-07 17:51
@niemyjski is probably making the same mistake I've made many times, using the JSON from the event page, rather than the JSON you can find in the web hook area, which includes additional "wrapping" JSON around the event data:

```js
{
  "id": "evt_...",
  "object": "event",
  "api_version": "2019-03-14",
  "created": 1559926811,
  "data": {
    // this is where your event data goes
  },
  "livemode": false,
  "pending_webhooks": 1,
  "request": {
    "id": null,
    "idempotency_key": null
  },
  "type": "invoice.created"
}
```

It would be nice if there was an easy way to copy the entire event JSON directly from the event detail page itself, rather than having to go down into the web hook detail area, and expand that out.

**Comment by niemyjski** [comment] 2019-06-10 01:37
Yeah, that is exactly what happened to me.
Thanks
-Blake Niemyjski

**Comment by ob-stripe** [comment] 2019-06-11 00:39
I see, thanks for the clarification!

Since this is not an issue with the library, I'm going to close this issue, but I'll file a ticket internally to improve the dashboard event view and make it clear that the default view only includes `event.data` and not the full event payload.

**Comment by niemyjski** [comment] 2019-06-11 00:52
Kind of is an issue with this library.. calling tojson should produce a result that round trips

**Comment by winzig** [comment] 2019-06-11 01:03
@niemyjski Can you show your full code, and where it fails? The code in your OP seems to be missing the part that generated the error message shown. E.g. where are you calling `Stripe.EventUtility.ParseEvent`

**Comment by ob-stripe** [comment] 2019-06-11 01:14
I might have misunderstood.

If you were trying to deserialize an `Event` object using the payload shown on an event's page in the dashboard, then it is expected this would fail because that payload is for an event's [`data`](https://stripe.com/docs/api/events/object#event_object-data) attribute and not for a full event object.

If you're saying that serializing an `Event` object by calling `ToJson()`, then deserializing that JSON string using either `Event.FromJson(json)` / `JsonConvert.DeserializeObject<Event>(json)` or `EventUtility.ParseEvent(json)` fails, then that would indeed be an issue with the library.

I've just tried it though and AFAICT it works fine. Could you provide minimal code to reproduce the issue, as well as the exact JSON payload of the event?

**Comment by niemyjski** [comment] 2019-06-11 12:00
I used the code in my first post, and this line of code to parse:

```cs
var client = new Stripe.ChargeService("test");
var charge = await client.GetAsync("id");
string json = charge.ToJson();
...
var stripeEvent = StripeApi.EventUtility.ParseEvent(json), throwOnApiVersionMismatch: false);
```

I'd rather not post the json due to possibly leaking customer data but it was as described by `@winzig commented 4 days ago`. It was just the inner object and not the event. As such I can't round trip it... The `charge.ToJson()` should be outputting everything required as shown below (which is missing):

```json
{
  "id": "evt_...",
  "object": "event",
  "api_version": "2019-03-14",
  "created": 1559926811,
  "data": {
    // this is where your event data goes
  },
  "livemode": false,
  "pending_webhooks": 1,
  "request": {
    "id": null,
    "idempotency_key": null
  },
  "type": "invoice.created"
}
```

**Comment by niemyjski** [comment] 2019-06-11 12:02
For example, if I have an event sourced store, I might want to write all these payloads to disk and replay them. But we use these events to unit test our integrations with real data (with a few things removed for p2).

**Comment by remi-stripe** [comment] 2019-06-11 12:05
@niemyjski When you call `.ToJson()` on a Stripe object, it just creates the JSON representation of that object. In your case, it creates the JSON associated with the Charge object as documented [here](https://stripe.com/docs/api/charges/object).

There is no way for that resource to create the JSON associated with an Event since this is a different resource in the API as documented [here](https://stripe.com/docs/api/events/object).

Events are a representation of the state of a given resource at a point in time. They have event-related properties (when was this event created, what type of event is it, etc.) and they also have the `data` hash which represents the associated resource. A `charge.succceeded` event would represent a Charge, while a `customer.created` event would describe a Customer.

**Comment by ob-stripe** [comment] 2019-07-08 01:26
Closing since this is not an issue with the library.

**Closed by ob-stripe** 2019-07-08 01:26 UTC
