### ISSUE TITLE
throwOnApiVersionMismatch flag is not working using EventUtility.ConstructEvent

### ISSUE THREAD

**Issue by matthewrwilliams** [stripe/stripe-dotnet#1556] opened 2019-03-19 15:22 UTC
I am using the following call:

`EventUtility.ConstructEvent(JSON, Request.Headers["Stripe-Signature"], _secret, throwOnApiVersionMismatch: false);`

I am still getting the following error.  It appears the flag `throwOnApiVersionMismatch` doesn't work?

> Received event with API version 2019-03-14, but Stripe.net 24.6.0 expects API version 2019-02-19. We recommend that you create a WebhookEndpoint with this API version. Otherwise, you can disable this exception by passing `throwOnApiVersionMismatch=false` to `Stripe.EventUtility.ParseEvent` or `Stripe.EventUtility.ConstructEvent`, but be wary that objects may be incorrectly deserialized.

**Comment by remi-stripe** [comment] 2019-03-19 15:25
@matthewrwilliams We haven't yet added support for this API version in the library as we were releasing other important changes that should go out before that one. You can follow along in this PR https://github.com/stripe/stripe-dotnet/pull/1552 where I'm going to do the work now.

In the meantime, we recommend that you always create a webhook endpoint set to the same API version as what the library supports. This is done by setting `ApiVersion` on `WebhookEndpointCreateOptions`. This ensures that you always get events formatted with the right API version.

**Comment by remi-stripe** [comment] 2019-03-19 15:35
@matthewrwilliams Events are always formatted on creation based on the API version associated with your webhook endpoint, if any, or the account's default API version. Once the event is generated, it can never be changed and it is immutable. You can not retrieve the event with a different API version for example as it would not work.

Since the library is pinned to a specific API version, it can only support that API version. Whenever you upgrade the library, you should add a second webhook endpoint with the API version set to this library's API version. That way, when you receive the event, the new code, with the new version of the library can properly deserialize the event. For a little while, you could keep both endpoints active so that we create events formatted for both API versions. That way your old code can listen to the old endpoint's URL and get events formatted on the old API version while your new code would listen to the new URL and get events formatted with the new API version.

The fact that your subscriptions last 12 months should not matter here. Events only matter at the time they are created. You can always modify an existing subscription based on a new API version without any issue. It's just that you need to keep in sync the version of the library and the API version associated with the webhook endpoint.

**Comment by matthewrwilliams** [comment] 2019-03-19 15:39
@remi-stripe That helps and clears up subscriptions.  Thank you.  

What about the flag... what should the flag `throwOnApiVersionMismatch` be used for?

**Comment by remi-stripe** [comment] 2019-03-19 15:42
By default, the library will error out if the event you are trying to deserialize does not match the API version of the library. This is to prevent crashes and partial deserializations.

But in a lot of cases, events would deserialize just fine. This is due to the fact that one new API version changes some behaviour but rarely touches most objects. For example, with the `2019-03-14` API version, we only removed some minor properties on invoices and the rest of the changes are behavioural changes. So any events about a Charge or a Refund would not have changed and could still be deserialized. For that reason we added the option to try to deserialize anyway though it's always risky.

Recently though, we added the option to have the webhook endpoint's API version in sync with the library (it shipped around a month ago) and this is now the recommended approach.

**Comment by ob-stripe** [comment] 2019-03-19 17:09
I'm surprised that you're getting this exception when passing `throwOnApiVersionMismatch: false` though, since it's specifically meant to _not_ throw this exception. 🤔

**Comment by matthewrwilliams** [comment] 2019-03-19 17:54
Correct, this was my concern as well.  I am not getting a serialization error, I am getting the specific error I pasted above.  Over 5,000 of them to be exact.  This is a test environment where I wanted to see what would happen with an upgrade.  I am working on a solution, but if that flag worked, it would save a lot of time.

**Comment by ob-stripe** [comment] 2019-03-19 17:59
@matthewrwilliams If it's not too much trouble, could you try to reproduce the issue with just:

```dotnet
var event = EventUtility.ParseEvent(JSON, throwOnApiVersionMismatch: false);
```

and let me know if that raises the same exception?

**Comment by matthewrwilliams** [comment] 2019-03-19 18:32
No exception using ParseEvent with the throwOnApiVersionMismatch set to false and upgrading to the latest 2019-03-14 API using version 24.6.0 of Stripe.net.

**Comment by ob-stripe** [comment] 2019-03-19 19:08
@matthewrwilliams Thanks. Could you try the following?

```c#
var event = EventUtility.ConstructEvent(
    JSON,
    Request.Headers["Stripe-Signature"],
    _secret,
    300,
    (long)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;
    false);
```

**Comment by matthewrwilliams** [comment] 2019-03-20 16:45
@ob-stripe that worked as well.  I am going to upgrade to the new version this morning and I'll test once the API upgrades the next time and let you know.  I needed to move on unfortunately, but would be happy to test next time.

**Comment by ob-stripe** [comment] 2019-03-20 17:03
No worries, thanks for the help so far! I'll keep this issue open for the time being and see if I can reproduce on my end.

**Comment by zyxnowell** [comment] 2019-04-08 02:53
I am also currently facing this problem, currently using version 24.5.0 and when using what @ob-stripe said, it works but I'm worried if I will set `throwOnApiVersionMismatch : false` it would cause an issue later on if there will be changes to the event objects. I am new to Stripe and just familiarizing things and just wanted to make sure that there would be less headaches for me in the future.

**Comment by remi-stripe** [comment] 2019-04-08 15:28
@zyxnowell The best solution now is to create a WebhookEndpoint with the API version forced to the same API version as the library. This ensures that deserialization would always succeed. In the future, if you upgrade the library, you would replace your old endpoint by a new one forced to the new API version that the library is pinned to: https://stripe.com/docs/api/webhook_endpoints/create#create_webhook_endpoint-api_version

**Comment by zyxnowell** [comment] 2019-04-09 03:15
@remi-stripe I see, that makes sense. Thanks very much!

**Comment by ob-stripe** [comment] 2019-04-12 17:01
@zyxnowell Correct, at the moment setting the API version for a webhook endpoint can only be done via the API, not the dashboard.

**Comment by ob-stripe** [comment] 2019-06-11 01:26
I'm closing this issue due to age and the fact that I was never able to reproduce the described problem, but please feel free to reply if you're still observing this issue!

**Closed by ob-stripe** 2019-06-11 01:26 UTC
