### ISSUE TITLE
List PaymentMethod is in dead lock and always timeout in version 27.0.0

### ISSUE THREAD

**Issue by loyalpocket** [stripe/stripe-dotnet#1653] opened 2019-06-10 11:57 UTC
var service = new PaymentMethodService();
var options = new PaymentMethodListOptions
{
CustomerId = customerId,
Limit = 1,
Type = "card"
};
var paymentMethods = service.List(options);

This function is in dead lock and always timeout in version 27.0.0.
Changed back to 26.1.0 then works fine.

**Comment by chriswindram** [comment] 2019-06-10 12:51
I am also experiencing the above in PaymentMethodListOptions, but also on the most simple of customer fetches:

var service = new CustomerService();
var customer = service.Get("cus_xxxxxxxx");

It locks in 27.0.0, but fine in 26.1.0. Interestingly, and for reasons I cannot explain, it seems to work in a console project, but not a web project (the same code called using the same API versions). When reverting to 26.1.0 it all works again.

**Comment by TomGullen** [comment] 2019-06-10 12:55
Can confirm experiencing same/similar problems.  Various requests seem to timeout and cause all sorts of issues.

**Comment by TomGullen** [comment] 2019-06-10 13:05
Rolling back to 26.0.1 has same issues, but 26.0.0 works fine.  Have rolled back to 26.0.0 for now.

Environment:
Windows
.net 4.7.2
IIS v 1803

**Comment by ob-stripe** [comment] 2019-06-10 15:20
@loyalpocket @chriswindram Could you share information about your environment? OS, version, target framework, etc.

**Comment by chriswindram** [comment] 2019-06-10 15:25
Hi ob-stripe,

I'm running Visual Studio 15.9.12 in Windows 10, with the project being a webforms project using .net framework 4.7.1. 

As per my previous note, one oddity that I cannot explain is that the very same code (called in the same dll) runs fine called from a console app with the same framework versioning etc.

Please let me know if I can provide anything that is of more help.

Kind regards,

Chris

**Comment by ob-stripe** [comment] 2019-06-10 17:08
Hi @chriswindram, thanks for the additional information. This is indeed very strange. I've tried reproducing in an ASP.NET Core app but to no avail.

Can you let me know how you set the API key? Via `StripeConfiguration.ApiKey = ...` or some other mean (e.g. creating a custom `StripeClient`)?

Also, can you check in your account's logs at https://dashboard.stripe.com/logs if you see the requests your app should be sending?

**Comment by chriswindram** [comment] 2019-06-10 17:14
Hi @ob-stripe,

I had updated to use StripeConfiguration.ApiKey = , as I saw that StripeConfiguration.SetApiKey was deprecated.

In the logs, it is showing the requests that hung, as 200 OK's, with the info:
Status: 200
Version: 2019-05-16 (latest)
Source: Stripe/v1 .NetBindings/27.0.0

So, it looks like the request was made ok, but something hung-up after that.

**Comment by ob-stripe** [comment] 2019-06-10 17:15
@chriswindram Thanks, that's very helpful. Can you share one of the request IDs? It's the string that starts with `req_` that can be found at the end of the URL when viewing a particular log entry.

**Comment by chriswindram** [comment] 2019-06-10 17:22
@ob-stripe Of course, try req_ViCrubvh9LqFit or req_3k2EkRKjOPL3xd or req_epeNtkP459vmjq

They're all showing as "200 OK", but hung in the webforms project. As I say, calling from a console project didn't hang. I'm sure that's got to suggest something, but I can't think of what for-the-life-of-me!  I did wonder about system.net.http being an issue, but both the console and webforms app used the same version.

**Comment by ob-stripe** [comment] 2019-06-10 17:46
@chriswindram Thanks! Looking at your logs, I see that each request to `/v1/customers/<cus_id>` is immediately followed by another request to `/v1/customers/<cus_id>/sources` with `object=card` and `limit=100`.

In your code, are you sending a `CardService.List` request? If so it looks like that's the request that hangs for some reason. Can you share a simplified version of your code?

(Really appreciate your help here -- I'm still trying to reproduce this on my end but no luck so far 😢)

**Comment by chriswindram** [comment] 2019-06-10 17:57
@ob-stripe Yes, at that time of testing I was doing the customer lookup prior to a card list request. I was pretty sure it was the customer line it was hanging-up on though in my debugger?  The code is essentially just:

StripeConfiguration.ApiKey = "xxx";

var custservice = new CustomerService();
var customer = custservice.Get("cus_xxx"); // It was here in the debugger that it hung

var service = new CardService();
var options = new CardListOptions { Limit = 100 };
var cards = service.List(customer.Id, options);

with a few additional checks-and-balances around it.

I am presently writing the code to move from charges to paymentintents in readiness for the Sept 1st deadline, so I will have lots of repetitive test calls in there under the 26.1 api (which is currently working fine for me).

**Comment by MarkA1** [comment] 2019-06-10 20:44
Seeing the same in 27.1.0 on a cardService.List(id) call. 

Examples:

- req_LJPh16wDNHFv9O
- req_P5xLMt68xH4DXv
- req_CvCzsLeM3Ngc6A

**Comment by ob-stripe** [comment] 2019-06-10 21:13
@MarkA1 Can you share information about your environment? (OS, version, target framework, etc.)

**Comment by MarkA1** [comment] 2019-06-10 21:49
@ob-stripe,

- Visual Studio Community 2019 (16.1.1)
- IIS Express
- Running on Windows 10 on a MacBook Pro under Parallels
- Target Framework .Net Framework 4.7.1

**Comment by ob-stripe** [comment] 2019-06-10 22:05
@MarkA1 (or anyone else having this issue) Thanks! One more questions: have you enabled [automatic retries](https://github.com/stripe/stripe-dotnet#configuring-automatic-retries)?

**Comment by MarkA1** [comment] 2019-06-10 22:10
@ob-stripe - I have not enabled or tried with the new automatic retries.

**Comment by MarkA1** [comment] 2019-06-10 22:50
@ob-stripe - I just tested with StripeConfiguration.MaxNetworkRetries = 2;  just to cross it off the list.  No change with it enabled.  

There are no exceptions thrown, and right at the call to CardService.List the debug session just seems to stop capturing break points for the rest of the method.

If I'm not in a debug session it seems to lock up IIS Express, requiring a restart.  Have also seen this lockup once while testing in debug mode and had to restart IIS afterward (Visual Studio times out on attempting to connect to IIS for debug on subsequent attempt until restarted).

**Comment by ob-stripe** [comment] 2019-06-10 23:44
Thanks everyone for all the information provided. I was able to reproduce the issue and I think I fixed the bug. A fixed version will be released soon.

**Closed** 2019-06-10 23:54 UTC

**Comment by ob-stripe** [comment] 2019-06-11 00:00
The issue should be fixed in version 27.1.2 which will appear on NuGet soon. Apologies for the inconvenience this caused, and thanks again everyone for helping pinpoint the issue.

Please feel free to reply here to report if the updated version fixed the issue for you or not.

**Comment by MarkA1** [comment] 2019-06-11 00:19
@ob-stripe - 27.1.2 did the trick.  It's fixed and working for me.  Thanks for the quick turn-around!

**Comment by chriswindram** [comment] 2019-06-11 08:04
@ob-stripe 27.1.2 is working for me also. Thanks for your hard work on getting to the bottom of that and fixing it.

**Comment by TomGullen** [comment] 2019-06-11 08:07
Works for me also, thank you!
