### ISSUE TITLE
Execution error on new install

### ISSUE THREAD

**Issue by agilealtitude** [stripe/stripe-dotnet#1510] opened 2019-02-11 19:57 UTC
Getting "Could not load file or assembly 'System.Net.Http, Version=4.0.0.0... when trying to run Quickstart sample. Nuget package installed successfully.

**Comment by ob-stripe** [comment] 2019-02-11 20:14
@agilealtitude Can you provide more information about your environment? Which OS and .NET version are you using?

**Comment by agilealtitude** [comment] 2019-02-11 20:17
Windows 10 Pro, latest updates. Using .Net 4.7.1, MVC 5.

**Comment by ob-stripe** [comment] 2019-02-11 21:36
@agilealtitude Okay, I did some research and I think this StackOverflow question describes the issue you're seeing: https://stackoverflow.com/questions/38408167/could-not-load-file-or-assembly-system-net-http-version-4-0-0-0-culture-neutr.

The workaround provided in the top answer here: https://stackoverflow.com/a/42542010/5307473 is confirmed as the correct one by a Microsoft engineer in this GitHub thread: https://github.com/dotnet/corefx/issues/25773#issuecomment-350000563.

This seems to be more of a bug with .NET Framework and/or Visual Studio and I don't think we can fix this in Stripe.net itself, so I'm going to close the issue, but please feel free to reply if the above link doesn't help or if you think this is actually a bug with Stripe.net.

**Closed by ob-stripe** 2019-02-11 21:36 UTC

**Comment by agilealtitude** [comment] 2019-02-12 02:00
Thank you for the follow up. I really appreciate you looking into it. I’m just wondering why I seem to be the only one having this problem?

**Comment by bora-fsd** [comment] 2019-06-03 21:06
Can confirm that this happened to me as well and the suggested solution in StackOverflow fixed it (Windows 10, .NET 4.7.1 MVC5)
