### ISSUE TITLE
PeriodStart and PeriodEnd appear to be a month behind

### ISSUE THREAD

**Issue by kawaicheung** [stripe/stripe-dotnet#1611] opened 2019-05-07 16:33 UTC
I'm using .NET 4.5.2 with Stripe.net 19.9.2.

I have a fairly normal subscription setup where customers start with a one-month trial and are billed on a monthly-recurring basis.

When grabbing all Stripe invoices via the `StripeInvoiceService`, it appears that the `PeriodStart` and `PeriodEnd` dates are a month behind, compared to the values found in the corresponding PDF invoice directly under the description field.

![Screen_Shot_2019-05-07_at_11_31_58_AM](https://user-images.githubusercontent.com/2701384/57316651-e6823900-70bb-11e9-8c56-d5ac0e8278a2.png)

-Ka Wai

**Comment by remi-stripe** [comment] 2019-05-07 16:55
@kawaicheung  This os expected behaviour. So the `period_end` and `period_start` corresponds to the period the invoice is for. As a rule on our end, the invoice is always for the "previous" period while the line item for the subscription is always for the new month.

This means that if you have a monthly subscription on the 1st of the month, the invoice on the 1st of November will be for the 1st of October until the 1st of November while the line item for the subscription will be for 1st of November to the 1st of December.

You need to look at the line item's period to show that date.

If you have any follow-up questions, make sure to ask our support team [here](https://support.stripe.com/contact) instead as they can help answer any API question. This is not a bug with the library itself so closing this issue!

**Closed by remi-stripe** 2019-05-07 16:55 UTC

**Comment by kawaicheung** [comment] 2019-05-07 16:59
I see - will do. thanks @remi-stripe!
