### ISSUE TITLE
Support for editing billing details CC email addresses

### ISSUE THREAD

**Issue by MarkA1** [stripe/stripe-dotnet#1599] opened 2019-05-01 15:46 UTC
We would like to see the ability to access/modify the Billing Details CC email address field via the API.  We do all of our customer creation, editing and invoice creation in our application and this important field seems to be inaccessible currently via the API.

**Comment by remi-stripe** [comment] 2019-05-01 16:07
@MarkA1 At the moment, this is not in the stripe-dotnet library because it's not available in the API yet. I'll raise this internally to see if it's something we can ship publicly and in that case it would make it to the library immediately!

Closing the issue since it's not a bug with the library and a limitation of the API instead.

**Closed by remi-stripe** 2019-05-01 16:07 UTC
