### ISSUE TITLE
ProductService.Create : Stripe.StripeException: 'Received unknown parameter: statement_descriptor'

### ISSUE THREAD

**Issue by chrisofthecoffee** [stripe/stripe-dotnet#2046] opened 2020-05-14 05:59 UTC
Running 36.12.2, trying to creating a product with StatementDescriptor supplied, returns exception saying statement_descriptor unknown.

Have run it with source linked up and followed it through down to MakeRequestAsync with all going smoothly, but the response comes back Bad Request from call to v1/products endpoint.

![image](https://user-images.githubusercontent.com/17450109/81897800-ea5b6c00-95e9-11ea-9dab-f414ac98dac5.png)
![image](https://user-images.githubusercontent.com/17450109/81897812-efb8b680-95e9-11ea-950c-c940f799acc7.png)

**Comment by remi-stripe** [comment] 2020-05-14 06:06
@chrisofthecoffee The problem here is that you seem to be creating a `Product` with `type: "good"`. Those do not support `statement_descriptor` as a parameter so that's why you get a 400. 

We recommend not creating those types of products anymore as they were specifically for SKUs which are considered deprecated. Instead use a normal `Product` without `type` at all and then use the new `Price` resource https://stripe.com/docs/billing/prices-guide

I'm going to close this issue as this is not a bug in the library itself. If you have follow up questions, don't hesitate to ask our support team for help: https://support.stripe.com/contact

**Closed by remi-stripe** 2020-05-14 06:06 UTC

**Comment by chrisofthecoffee** [comment] 2020-05-14 06:15
Ah got you, thanks - I've retried it without specifying the type property and all went smoothly (well, after I'd truncated StatementDescriptor to 22 characters), I have my first product.
