### ISSUE TITLE
Missing Source.Card object when creating a charge

### ISSUE THREAD

**Issue by kevinits** [stripe/stripe-dotnet#1505] opened 2019-02-07 11:07 UTC
I'm trying to update to Version 22.8.1.0.  However, I used to be able to do the following so that I can store some information about the card in our database.  We use it for searching and verification purposes when someone calls, asking about their order.

```vb.net
Dim stripeCharge As Stripe.Charge = chargeService.Create(myCharge, requestOptions)
chargeId = stripeCharge.Id
cardType = stripeCharge.Source.Card.Brand
lastFour = stripeCharge.Source.Card.Last4
expMonth = stripeCharge.Source.Card.ExpirationMonth
expYear = stripeCharge.Source.Card.ExpirationYear
```

In this new version, there's no Card object in the Source object.  I've searched everywhere and can't seem to find an alternative location.  Can I still get this when creating a charge or do I have to make a separate call?

**Comment by ob-stripe** [comment] 2019-02-07 11:27
Hi @kevinits. In version 20, we changed the way polymorphic attributes are handled. They are now represented by interfaces, e.g. the [`Charge.Source`](https://github.com/stripe/stripe-dotnet/blob/9a8a933d0796bad9e8a199894b66b7d98392641a/src/Stripe.net/Entities/Charges/Charge.cs#L423) property is now an [`IPaymentSource`](https://github.com/stripe/stripe-dotnet/blob/9a8a933d0796bad9e8a199894b66b7d98392641a/src/Stripe.net/Entities/_interfaces/IPaymentSource.cs#L22), which can be one of several concrete types. (You can read more about this in the [migration guide for v20](https://github.com/stripe/stripe-dotnet/wiki/Migration-guide-for-v20#interfaces-for-polymorphic-resources).)

If you know that the source will be a `Card`, you can directly cast the property to the concrete type. I'm not familiar with VB but I think something like this should work:

```vb.net
Dim stripeCharge As Stripe.Charge = chargeService.Create(myCharge, requestOptions)
Dim card As Stripe.Card = CType(stripeCharge.Source, Stripe.Card)
cardType = card.Brand
' etc.
```

If you don't know the type in advance (e.g. because your integration handles different payment methods), you'll need to check the type at runtime:

```vb.net
Dim stripeCharge As Stripe.Charge = chargeService.Create(myCharge, requestOptions)
If TypeOf stripeCharge.Source Is Stripe.Card Then
  Dim card As Stripe.Card = CType(stripeCharge.Source, Stripe.Card)
  ' Do something with card
ElseIf TypeOf stripeCharge.Source Is Stripe.BankAccount Then
  Dim bankAccount As Stripe.BankAccount = CType(stripeCharge.Source, Stripe.BankAccount)
  ' Do something with bankAccount
ElseIf TypeOf stripeCharge.Source Is Stripe.Source Then
  Dim source As Stripe.Source = CType(stripeCharge.Source, Stripe.Source)
  ' Do something with source
Else
  ' Unexpected type, log an error
End
```

Closing the issue since it's not a bug or feature request for the library, but feel free to reply if needed.

**Closed by ob-stripe** 2019-02-07 11:27 UTC

**Comment by kevinits** [comment] 2019-02-07 11:38
Wow, thank you so much for the quick reply.  It works perfectly.  I apologize for not noticing those migration pages on the Wiki.  I'll make sure to look for those in the future.

**Comment by ob-stripe** [comment] 2019-02-07 12:25
No worries! Glad I could help :)
