### ISSUE TITLE
Stripe.net (version 39.63.0)- missing charges.Data for Canadian bank debits "acss_debit"

### ISSUE THREAD

**Issue by abereznyi** [stripe/stripe-dotnet#2364] opened 2021-08-23 17:24 UTC
When payment method is "acss_debit" no payment detail is available in intent:

                var sessionService = new SessionService(provider.StripeClient);
                var session = await sessionService.GetAsync(session_id);

                var intentService = new PaymentIntentService(provider.StripeClient);
                var intent = await intentService.GetAsync(session.PaymentIntentId);

                var charges = intent.Charges;  
                ChargePaymentMethodDetails paymentMethodDetails; // comes from charges.Data[0].PaymentMethodDetails
                
But charges.Data.Count == 0 here unlike all other payment methods. Looks like a bug.

I found a workaround for this case - get "acss_debit" details via PaymentMethodService API:
                   var id = intent.PaymentMethodId;
                    var svc = new PaymentMethodService(provider.StripeClient);
                    var pm = await svc.GetAsync(id);

Also the Success status returned is "unpaid" - something like "pending" would make more sense, as "acss_debit" takes about 5 business days to complete.

**Comment by remi-stripe** [comment] 2021-08-24 00:32
@abereznyi ACSS Debit is an async payment method. This means you pay today and it takes up to 7 days for the payment to succeed or fails. When that happens the **PaymentIntent** is in `status: 'processing'` in that case and no **Charge** is created until we know whether it succeeded or failed. Nothing is missing here and it's expected behaviour.

I'm going to close this ask as it's more an integration question and not a bug with the library itself. If you have more questions on this one I'd recommend joining our Discord server: https://stripe.com/go/developer-chat

**Closed by remi-stripe** 2021-08-24 00:32 UTC
