### ISSUE TITLE
Invalid Product Url (2048 characters or less)

### ISSUE THREAD

**Issue by emt2dev** [stripe/stripe-dotnet#2964] opened 2024-09-06 20:42 UTC
### Describe the bug

Hello, I'm attempting to create a product using .NET 8.

**URL used:** "https://localhost:3000/product/2"
**Exception Received when calling the product service:** Stripe.StripeException: 'Invalid URL: URL must be 2048 characters or less.'

### To Reproduce

            ProductPackageDimensionsOptions NewPackageDimensions = new ProductPackageDimensionsOptions
            {
                Height = Convert.ToDecimal(Obj.Height), // inches
                Length = Convert.ToDecimal(Obj.Length), // inches
                Width = Convert.ToDecimal(Obj.Width), // inches
                Weight = Convert.ToDecimal(Obj.Weight) // ounces
            };

            var NewStripeProduct = new ProductCreateOptions
            { // DefaultPrice turns this into a service
                Name = Obj.Name,
                Type = "good", // good = orders and skus, service = subscription/plan (this is the default)
                Description = Obj.Description,
                PackageDimensions = NewPackageDimensions,
                Shippable = true, // ProductPackageDimensionsOptions PackageDimensions
                TaxCode = Obj.TaxCode, // found on stripe docs
                Url = Obj.PublicURL, // url for the product.
                Metadata = new Dictionary<string, string>(),
                Images = new List<string> { Obj.Image }
            };

            NewStripeProduct.Metadata.Add("StoreId", StoreId.ToString());

            var serviceProduct = new ProductService();
            Product product = serviceProduct.Create(NewStripeProduct);

### Expected behavior

I am expecting to be able to create a product using the stripe api's product service with a valid URL that is less than 2048 characters.

![image](https://github.com/user-attachments/assets/43f376f4-3b55-424c-8dc6-7bb9ddb2f271)
![image](https://github.com/user-attachments/assets/8144c840-3bfb-46bc-83f9-f1eb57401a58)

### Code snippets

```csharp
ProductPackageDimensionsOptions NewPackageDimensions = new ProductPackageDimensionsOptions
            {
                Height = Convert.ToDecimal(Obj.Height), // inches
                Length = Convert.ToDecimal(Obj.Length), // inches
                Width = Convert.ToDecimal(Obj.Width), // inches
                Weight = Convert.ToDecimal(Obj.Weight) // ounces
            };

            var NewStripeProduct = new ProductCreateOptions
            { // DefaultPrice turns this into a service
                Name = Obj.Name,
                Type = "good", // good = orders and skus, service = subscription/plan (this is the default)
                Description = Obj.Description,
                PackageDimensions = NewPackageDimensions,
                Shippable = true, // ProductPackageDimensionsOptions PackageDimensions
                TaxCode = Obj.TaxCode, // found on stripe docs
                Url = Obj.PublicURL, // url for the product. (for testing, I've also tried "test" or "https://localhost:3000/product/2" instead of the object's property.
                Metadata = new Dictionary<string, string>(),
                Images = new List<string> { Obj.Image }
            };

            NewStripeProduct.Metadata.Add("StoreId", StoreId.ToString());

            var serviceProduct = new ProductService();
            Product product = serviceProduct.Create(NewStripeProduct);
```

### OS

windows 11

### .NET version

.net 8

### Library version

45.11.0

### API version

2024-06-20

### Additional context

i tested this a few weeks ago and it worked. Not sure, why this isn't.

**Comment by emt2dev** [comment] 2024-09-06 21:30
I spun up stripe-mock and forked the repo; i then passed the url into the test and the test was successful:
![Screenshot 2024-09-06 172847](https://github.com/user-attachments/assets/3a227805-1c26-4d00-87d1-f16bfec23b39)
![Screenshot 2024-09-06 172859](https://github.com/user-attachments/assets/c62c8e99-5df0-464a-92e2-9172767e2f62)

**Comment by remi-stripe** [comment] 2024-09-06 23:14
The problem in your code is with the `Images` parameter instead. This is supposed to be an array of **URLs** and I think you are passing the raw content of the files instead which is not supported.
You can confirm it's the issue by looking at your logs in Test mode in the Dashboard at https://dashboard.stripe.com/test/logs and then looking up one of those errors. It should show all your parameters and you will see the `Images` one you passed is not what you think.

I'm going to close this out as it's not a bug with the SDK and is instead and integration support question. If you have follow up questions, please work with our support team directly here: https://support.stripe.com/contact

**Closed by remi-stripe** 2024-09-06 23:14 UTC
Labels: bug
