### ISSUE TITLE
EphemeralKey does not have a secret field

### ISSUE THREAD

**Issue by BenderNK** [stripe/stripe-dotnet#2269] opened 2021-01-05 06:21 UTC
Hello, 

We are in the process of integrating with Stripe iOS. Our backend is .Net Core 3.1. We are currently testing the integration in the dev environment so the data I'll share in this ticket is not for real customers.

The issue we are having is with the ephemeral keys. We can successfully obtain the key as in the following:
```
{
    "id": "ephkey_1I686AK76.....",
    "object": "ephemeral_key",
    "associated_objects": [
        {
            "id": "cus_Ih7R.....",
            "type": "customer"
        }
    ],
    "created": 1609824530,
    "expires": 1609828130,
    "livemode": false
}
```
But this ephemeral key is not parseable by the iOS client because it expects the `secret` key in the dictionary which clearly doesn't exist in the above JSON or in the EphemeralKey object definition in the .Net Stripe library as seen below:
```
public class EphemeralKey : StripeEntity<EphemeralKey>, IHasId, IHasObject
{
      public EphemeralKey();
      [JsonProperty("id")]

      public string Id { get; set; }
      [JsonProperty("object")]

      public string Object { get; set; }
      [JsonProperty("associated_objects")]

      public List<EphemeralKeyAssociatedObject> AssociatedObjects { get; set; }
      [JsonConverter(typeof(UnixDateTimeConverter))]

      [JsonProperty("created")]
      public DateTime Created { get; set; }

      [JsonProperty("deleted", NullValueHandling = NullValueHandling.Ignore)]
      public bool? Deleted { get; set; }
      [JsonConverter(typeof(UnixDateTimeConverter))]

      [JsonProperty("expires")]
      public DateTime Expires { get; set; }

      [JsonProperty("livemode")]
      public bool Livemode { get; set; }

      [JsonIgnore]
      public string RawJson { get; }
}
```

If one examines the **Ignored** RawJson field, the secret information can be found in there.

Anyhow, If the iOS SDK is right, Stripe .NET library has to include another field called "Secret" so that it can be properly serialized and be sent to the iOS client. If .NET library is right, then iOS SDK shouldn't look for that field within the EphemeralKey object while parsing. 

I am using the following versions and/or tools:
Stripe.net version 39.31.0
Stripe iOS Client SDK - version: 21.1.0 (Cocoapod)
STPCustomerEphemeralKeyProvider reports that it is using api version: 2020-08-27
XCode 12.3
.Net Core 3.1
JSON Serialization by NewtonSoft
For reference purposes, I am including the code that fails on the iOS SDK side:
```
STPEphemeralKey.swift
...
class func decodedObject(fromAPIResponse response: [AnyHashable: Any]?) -> Self? {
...
let secret = dict.stp_string(forKey: "secret"), // => this is the line that fails as the secret key simply doesn't exist in the EphemeralKey object
...
}
```

Guidance would be greatly appreciated.
Thanks

**Comment by remi-stripe** [comment] 2021-01-05 13:50
@BenderNK Flagging this is a duplicate of https://github.com/stripe/stripe-dotnet/issues/2105 but copying my answer from there to make it easier.

This is intentional on our end. You should never have to access an Ephemeral Key's secret yourself. Instead, you are supposed to returned the exact raw JSON our API returns to the mobile SDK. The reason is that mobile SDKs are pinned to a different API version than stripe-dotnet and so it can't be safely deserialized this way. Just use the `RawJson` property instead: https://github.com/stripe/stripe-dotnet/blob/master/src/Stripe.net/Entities/EphemeralKeys/EphemeralKey.cs#L54

If you return this raw string to the Mobile Android or iOS SDKs they will work as expected.

**Comment by BenderNK** [comment] 2021-01-05 14:55
Hello @remi-stripe.
Thanks for picking up this ticket and responding. Also thanks for the background info. It looks like other developer got also confused a bit. 

So I just want to make couple of things clear to make sure we are on the same page:
1. iOS SDK is looking for a field in the serialized ephemeral key object called "**secret**"
2. The ephemeral key object when serialized with NewtonSoft does not contain a field called "secret" (see the initial JSON)
3. iOS SDK causes a crash because of this missing field in the serialized object. I am getting an error from iOS SDK - basically saying please do not modify the ephemeral key object that you get from Stripe. Which I am not. I literally copied the code from Stripe's own integration guides.
4. Also to be clear, I am not trying to access the ephemeral key's secret myself. I am simply reporting where the crash occurs on the iOS SDK. Stripe's own code is looking for the key with the name "secret" which simply does not exist in the serialized object. 

Also for reference, allow me to copy the .net code I have which should be near identical to the one in the guides.
```
var options = new EphemeralKeyCreateOptions()
{
  Customer = request.CustomerId,
  StripeVersion = request.StripeVersion
}
  var service = new EphemeralKeyService();
  var ephemeralKey = service.Create(options);
  return Ok(ephemeralKey) //at this point, .Net Core 3.1 uses NewtonSoft to serialize the key
}
```
And this is the serialized output
```
{
    "id": "ephkey_1I686AK76.....",
    "object": "ephemeral_key",
    "associated_objects": [
        {
            "id": "cus_Ih7R.....",
            "type": "customer"
        }
    ],
    "created": 1609824530,
    "expires": 1609828130,
    "livemode": false
}
```

Looks like I might be missing a step.

**Comment by BenderNK** [comment] 2021-01-05 15:01
Apologies. I forgot to attach the screenshot of Stripe iOS SDK where it actually looks for the key "secret". 

![Screen Shot 2021-01-05 at 9 00 31 AM](https://user-images.githubusercontent.com/10276667/103661610-8ac51e80-4f34-11eb-8eaa-0dd2c1184511.png)

**Comment by BenderNK** [comment] 2021-01-05 19:03
Also re-reading the referenced issue of #2105, the reporter of that issue corroborates my findings here but softly protests that he has to do additional work to include the missing "secret" key in the ephemeral key response as seen here:
> The issue isn't so much that i can't get that value, I can, but i can't do it with the SDK classes - i do have to create my own model for the response from the server ! That's fine , i will do that but i was just expecting the SDK to have an appropriate class.
But as you said , it would make keeping track of API's hard and changes could break apps.

What the developer eventually agrees to do on his/her side is:
1. Manually parse the `RawJson` object from the EphemeralKey
2. Extract the "secret" value from there. 
3. Create another separate object (say `CustomEphemeralKey`) that includes this secret as well as all other fields of the original Stripe's EphemeralKey.
4. Serialize the CustomEphemeralKey instead and send that object to the client side instead.
5. And then manually keep track of the changes to Stripe's EphemeralKey object as any change in that would also necessitate changes to CustomEphemeralKey.

I guess that is my question. Why are these steps required? It almost feels like this is something dotnet library should do which is exactly what the person asks at the end of the [post](https://github.com/stripe/stripe-dotnet/issues/2105#issuecomment-653697939).

**Comment by remi-stripe** [comment] 2021-01-06 16:10
@BenderNK You don't need to do anything extra yourself. There is also no reason for you to _parse_ the raw JSON to extract the secret. All you need to do in your code is return the raw string from `RawJson` back to your client (the mobile SDK). The SDKs are built with that in mind, they get the raw JSON our API returned, which stripe-dotnet does not look at directly nor touch, and they parse the JSON themselves and extract all the information they need.

The issue I think here is that you are trying to serialize the object yourself. This does not work since the serialization only returns the properties that we explicitly parse which does not include the `Secret` one. This is done on purpose though to avoid mistakes in the future (due to API versioning changes).

Your code should look like this instead:

```
var options = new EphemeralKeyCreateOptions()
{
  Customer = request.CustomerId,
  StripeVersion = request.StripeVersion
}
  var service = new EphemeralKeyService();
  var ephemeralKey = service.Create(options);
  return ephemeralKey.RawJson; // here you return the raw JSON and let the iOS SDK handle it itself
}
```

**Comment by BenderNK** [comment] 2021-01-06 16:26
Thank you so much. This wasn't really clear to me after reading the guides. All the examples I have seen on Stripe's own documentation implies that you should be serializing the EphemeralKey itself. For example this guide finishes the example at the ephemeral key creation step and then as a developer you assume that the ephemeral key itself needs to be serialized.

![Screen Shot 2021-01-06 at 10 21 56 AM](https://user-images.githubusercontent.com/10276667/103792365-2a53e100-5009-11eb-805e-b4780945afb0.png)

Also the example backend written with Ruby doesn't help clarify it because in that example the key is actually being serialized. See screenshot.
![Screen Shot 2021-01-06 at 10 17 38 AM](https://user-images.githubusercontent.com/10276667/103792423-3f307480-5009-11eb-9399-b309a9133f2c.png)

Anyhow, do you mind keeping the ticket open for another day? I will test this out and confirm it for posterity.

**Comment by remi-stripe** [comment] 2021-01-07 13:07
Thanks for pointing out the confusion caused by the guides more explicitly, it helps better understand what trips up developers!
The ruby one is "special", or rather it's dotnet, go and java that are special because they are pinned to a specific API version which is usually different from the one the Mobile SDKs expect which would cause problems.
I'll flag internally to see if we can get the guides improved and add some explanation around how this works. In a way we really want the key to be "opaque" entirely since it's just an authentication scheme for Mobile SDKs but it has definitely been more confusing than planned.

**Closed by remi-stripe** 2021-01-07 13:07 UTC
