### ISSUE TITLE
Charge throwing an exception ?

### ISSUE THREAD

**Issue by fernandopaiva** [stripe/stripe-dotnet#1570] opened 2019-04-06 02:23 UTC
I'm trying make a charge using Stripe C# Library and it always throws an exception that I don't know how to fix.

Please, how could I fix this ?

**Charge**

```
public JsonResult Charge(PagtoPacoteModel model){
        if (ModelState.IsValid == false){
            jsonResposta.Add("status", "0");
            jsonResposta.Add("msg", "Informe todos os campos necessários");
            return Json(jsonResposta);
        }

        StripeConfiguration.SetApiKey(PagtoPacote.SECRET_KEY_TESTE);
        model.descricaoPacote = PagtoPacote.descricaoPacote;

        try
        {
            //hash cartao
            var cardOptions = new TokenCreateOptions
            {
                Card = new CreditCardOptions
                {
                    Name = model.nomePropCartao,
                    Number = model.numCartao,
                    ExpYear = Convert.ToInt64(model.anoVencimento),
                    ExpMonth = Convert.ToInt64(model.mesVencimento),
                    Cvc = model.cvv,
                    Currency = "brl",
                }
            };

            var svc = new TokenService();
            Token stripeToken = svc.Create(cardOptions);
            String token = stripeToken.Id;
            Debug.WriteLine(token); 

            //charge
            var chargeOptions = new ChargeCreateOptions
            {
                Amount = 100,
                Currency = "brl",
                Description = model.descricaoPacote,
                SourceId = token
            };

            var service = new ChargeService();
            Charge charge = service.Create(chargeOptions);

            Debug.WriteLine("Charge status: " + charge.Status);

            jsonResposta.Add("status", "1");
            jsonResposta.Add("msg", "Processamento executado com sucesso!");

        }
        catch (StripeException e)
        {
            jsonResposta.Add("status", "0");
            jsonResposta.Add("msg", "Erro: " + e.Message);
            Debug.WriteLine("Erro: " + e.InnerException);
        }
        
        return Json(jsonResposta);
    }
```

**Exception**

> An exception of type 'System.IO.FileLoadException' occurred in Newtonsoft.Json.dll but was not handled in user code
> 
> Additional information: Não foi possível carregar arquivo ou assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou uma de suas dependências. A definição do manifesto do assembly localizado não corresponde à referência do assembly. (Exceção de HRESULT: 0x80131040)

**Web.config**

```
<?xml version="1.0" encoding="utf-8"?>
<!--
  For more information on how to configure your ASP.NET application, please visit
  http://go.microsoft.com/fwlink/?LinkId=301880
  -->
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 --></configSections>
  <!--<connectionStrings>
    <add name="DefaultConnection" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-GerenciaDayTrade-20190310014548.mdf;Initial Catalog=aspnet-GerenciaDayTrade-20190310014548;Integrated Security=True" providerName="System.Data.SqlClient" />
  </connectionStrings>-->
  
  <!--string de conexao-->
  <connectionStrings>    
    <add name="default" connectionString="Server=127.0.0.1;Database=db_gdt;Uid=root;Pwd=;CharSet=utf8;" providerName="MySql.Data.MySqlClient" />    
  </connectionStrings>
  
  <appSettings>
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
  </appSettings>
  
  <system.web>
    
    <!--<globalization uiCulture="pt-BR" culture="pt-BR" enableClientBasedCulture="true" />-->

    <!--<trust level="Medium" originUrl="\"/>-->
    
    <!--Alterado-->
    <customErrors mode="Off" />

    <!--Alterado-->
    <authentication mode="Forms">
      <forms defaultUrl="~/Usuario/Login" loginUrl="~/Usuario/Login" slidingExpiration="true" timeout="2880" />
    </authentication>
    
    <compilation debug="true" targetFramework="4.5.2" />
    <httpRuntime targetFramework="4.5.2" />
    <httpModules>
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" />
    </httpModules>
    
  </system.web>
  
  <system.webServer>

    <!--Libera diretorio imagens-->
    <directoryBrowse enabled="true" />
    
    <modules>
      <!-- Alterado <remove name="FormsAuthentication" />-->
      <remove name="ApplicationInsightsWebTracking" />
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
    </modules>
    <validation validateIntegratedModeConfiguration="false" />
  </system.webServer>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.1.0" newVersion="3.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security.OAuth" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.1.0" newVersion="3.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security.Cookies" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.1.0" newVersion="3.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.1.0" newVersion="3.0.1.0" />
      </dependentAssembly>      
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>      
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Optimization" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-1.5.2.14234" newVersion="1.5.2.14234" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="MySql.Data" publicKeyToken="c5687fc88969c44d" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.10.8.0" newVersion="6.10.8.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.36.0" newVersion="1.1.36.0" />        
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />
    </providers>
  </entityFramework>
  
  <!--adicionar esse system.data-->
  <system.data>
    <DbProviderFactories>
      <remove invariant="MySql.Data.MySqlClient" />
      <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.9.10.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />
    </DbProviderFactories>
  </system.data>
  
  
  <system.codedom>
    <compilers>
      <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701" />
      <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
    </compilers>
  </system.codedom>
</configuration>
```

**Packages.config**

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net452" />
  <package id="bootstrap" version="3.3.7" targetFramework="net452" />
  <package id="Bootstrap.v3.Datetimepicker.CSS" version="4.17.45" targetFramework="net452" />
  <package id="BouncyCastle" version="1.7.0" targetFramework="net452" />
  <package id="EntityFramework" version="6.2.0" targetFramework="net452" />
  <package id="ExcelLibrary" version="1.2011.7.31" targetFramework="net452" />
  <package id="jQuery" version="1.10.2" targetFramework="net452" />
  <package id="jQuery.Validation" version="1.11.1" targetFramework="net452" />
  <package id="Microsoft.ApplicationInsights" version="2.0.0" targetFramework="net452" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="1.2.1" targetFramework="net452" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.0.0" targetFramework="net452" />
  <package id="Microsoft.ApplicationInsights.JavaScript" version="0.22.9-build00167" targetFramework="net452" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.0.0" targetFramework="net452" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.0.0" targetFramework="net452" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.0.0" targetFramework="net452" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.0.0" targetFramework="net452" />
  <package id="Microsoft.AspNet.Identity.Core" version="2.2.1" targetFramework="net452" />
  <package id="Microsoft.AspNet.Identity.EntityFramework" version="2.2.1" targetFramework="net452" />
  <package id="Microsoft.AspNet.Identity.Owin" version="2.2.1" targetFramework="net452" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net452" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net452" />
  <package id="Microsoft.Net.Compilers" version="1.0.0" targetFramework="net452" developmentDependency="true" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security.Cookies" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security.Facebook" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security.Google" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security.MicrosoftAccount" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security.OAuth" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Security.Twitter" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net452" />
  <package id="Modernizr" version="2.6.2" targetFramework="net452" />
  <package id="Moment.js" version="2.9.0" targetFramework="net452" />
  <package id="MySql.Data" version="6.10.8" targetFramework="net452" />
  <package id="MySql.Data.Entity" version="6.9.9" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="Owin" version="1.0" targetFramework="net452" />
  <package id="PagedList" version="1.17.0.0" targetFramework="net452" />
  <package id="PagedList.Mvc" version="4.5.0.0" targetFramework="net452" />
  <package id="Respond" version="1.2.0" targetFramework="net452" />
  <package id="Stripe.net" version="25.4.0" targetFramework="net452" />
  <package id="System.Collections.Immutable" version="1.5.0" targetFramework="net452" />
  <package id="WebGrease" version="1.5.2" targetFramework="net452" />
</packages>
```

**Comment by ob-stripe** [comment] 2019-04-06 04:22
Hi @fernandopaiva. I don't think this issue is caused by the Stripe.net library itself. Rather, it looks like you're having trouble with the `System.Collections.Immutable` dependency.

Googling for the (English) error message "Could not load find or assembly System.Collections.Immutable" yields a number of results, but it's not very clear what causes this or how to fix it exactly.

Some people in [this thread](https://github.com/aspnet/Mvc/issues/5539) reported that deleting the `bin` folder and flushing the Nuget cache solved the issue for them.

[This comment](https://github.com/Microsoft/msbuild/issues/1582#issuecomment-278937269) says that this is Visual Studio issue and offers a workaround.

I'm closing the issue since I'm fairly sure this is not a Stripe.net bug. Hopefully one of these links will help you. Feel free to reply if you're still having trouble or if you manage to solve the issue!

**Closed by ob-stripe** 2019-04-06 04:22 UTC

**Comment by fernandopaiva** [comment] 2019-04-06 05:34
@ob-stripe The Stripe library uses `System.Collections.Immutable` am I right ?

**Comment by ob-stripe** [comment] 2019-04-06 06:28
Yes, it's a dependency of Stripe.net: https://github.com/stripe/stripe-dotnet/blob/59acf3433f35233e264804f7c5c41a5812866839/src/Stripe.net/Stripe.net.csproj#L50
