### ISSUE TITLE
Get Payment Method issue

### ISSUE THREAD

**Issue by bahiyah** [stripe/stripe-dotnet#2313] opened 2021-05-05 02:57 UTC
There is a problem when using `PaymentMethodService.Get(paymentMethodId)` to get the PaymentMethod. 

The exception thrown was `The given key was not present in the dictionary.` at `System.Collections.Generic.Dictionary'2.get_Item(TKey key)`. We have confirmed that the customer's payment method exists in our account. And there was no problem retrieving the payment method previously.

We have checked our codes and narrowed the cause down to this function. 

The error started on May 4th, 2021. Prior to that, there was no problem.

**Comment by remi-stripe** [comment] 2021-05-05 03:10
@bahiyah The stripe-dotnet library has not been updated since April 16 so it wouldn't be a recent change in the API. I'm also able to retrieve a PaymentMethod via the API successfully and it deserializes properly.

My assumption here is that something unrelated changed on your end since May 4th. Maybe you changed .NET version, or maybe you're using a different version of `Newtonsoft.Json` for example and something is conflicting in the deserialization? Maybe `paymentMethodId` is null in your code? 
My recommendation is to start by figuring out what changed on your end in the past few days that could have caused this and understand whether other parts of your code are failing if it's just that specific one. Can you reproduce in Test mode? Does creating a PaymentMethod work properly? 

You would likely have more success with our support team as they can look at your account and its settings, look at your exact code and you can share logs with them to help you debug: https://support.stripe.com/contact

**Comment by bahiyah** [comment] 2021-05-05 03:55
@remi-stripe We first encounter the error on May 4th, 2021. Prior to this that, the last payment notification we received from Stripe is on April 4th. Therefore, we have not been retrieving the payment method through the API. 

We have also confirmed that the .NET version and `Newtonsoft.Json` version have not changed. We are able to deserialize the JSON sent to our webhook. We are able to create and send `PaymentIntent` too. The only error that we currently faced is to retrieve the `PaymentMethod`. Since the last update is April 16th, I guess we will begin by comparing the changes with what we have on our system.

I am still waiting for the support team to get back to me on this issue.

**Comment by richardm-stripe** [comment] 2021-10-04 15:27
I am closing this, as I do not think it indicates an issue with the stripe-dotnet library itself and is an integration problem or API issue that should be handled through support. Feel free to re-open with more details if you believe this not to be the case.

**Closed by richardm-stripe** 2021-10-04 15:27 UTC
